/opt/trinity/share/apps/kbounce/*
/opt/trinity/share/applications/tde/kbounce.desktop
/opt/trinity/share/icons/hicolor/16x16/apps/kbounce.png
/opt/trinity/share/icons/hicolor/22x22/apps/kbounce.png
/opt/trinity/share/icons/hicolor/32x32/apps/kbounce.png
/opt/trinity/share/icons/hicolor/48x48/apps/kbounce.png
/opt/trinity/share/icons/hicolor/64x64/apps/kbounce.png
/opt/trinity/share/icons/hicolor/128x128/apps/kbounce.png
/opt/trinity/games/kbounce
/opt/trinity/share/doc/tde/HTML/en/kbounce/*
../icons/kbounce.xpm /opt/trinity/share/pixmaps
../icons/kbounce-16.xpm /opt/trinity/share/pixmaps
