/opt/trinity/share/apps/kmahjongg/*
/opt/trinity/share/icons/hicolor/128x128/apps/kmahjongg.png
/opt/trinity/share/icons/hicolor/64x64/apps/kmahjongg.png
/opt/trinity/share/icons/hicolor/48x48/apps/kmahjongg.png
/opt/trinity/share/icons/hicolor/32x32/apps/kmahjongg.png
/opt/trinity/share/icons/hicolor/22x22/apps/kmahjongg.png
/opt/trinity/share/icons/hicolor/16x16/apps/kmahjongg.png
/opt/trinity/share/applications/tde/kmahjongg.desktop
/opt/trinity/games/kmahjongg
/opt/trinity/share/config.kcfg/kmahjongg.kcfg
/opt/trinity/share/doc/tde/HTML/en/kmahjongg/*
../icons/kmahjongg.xpm /opt/trinity/share/pixmaps
../icons/kmahjongg-16.xpm /opt/trinity/share/pixmaps
