/opt/trinity/share/apps/kpoker/*
/opt/trinity/share/icons/hicolor/128x128/apps/kpoker.png
/opt/trinity/share/icons/hicolor/64x64/apps/kpoker.png
/opt/trinity/share/icons/hicolor/48x48/apps/kpoker.png
/opt/trinity/share/icons/hicolor/32x32/apps/kpoker.png
/opt/trinity/share/icons/hicolor/22x22/apps/kpoker.png
/opt/trinity/share/icons/hicolor/16x16/apps/kpoker.png
/opt/trinity/share/applications/kde/kpoker.desktop
/opt/trinity/games/kpoker
/opt/trinity/share/doc/kde/HTML/en/kpoker/*
../icons/kpoker.xpm /opt/trinity/share/pixmaps
../icons/kpoker-16.xpm /opt/trinity/share/pixmaps
