/opt/trinity/games/ktron
/opt/trinity/share/icons/hicolor/16x16/apps/ktron.png
/opt/trinity/share/icons/hicolor/22x22/apps/ktron.png
/opt/trinity/share/icons/hicolor/32x32/apps/ktron.png
/opt/trinity/share/icons/hicolor/48x48/apps/ktron.png
/opt/trinity/share/icons/hicolor/64x64/apps/ktron.png
/opt/trinity/share/icons/hicolor/128x128/apps/ktron.png
/opt/trinity/share/doc/kde/HTML/en/ktron/*
/opt/trinity/share/applications/kde/ktron.desktop
/opt/trinity/share/apps/ktron/*
/opt/trinity/share/config.kcfg/ktron.kcfg
../icons/ktron.xpm /opt/trinity/share/pixmaps
../icons/ktron-16.xpm /opt/trinity/share/pixmaps
