/opt/trinity/games/lskat
/opt/trinity/games/lskatproc
/opt/trinity/share/doc/tde/HTML/en/lskat/*
/opt/trinity/share/apps/lskat/*
/opt/trinity/share/icons/hicolor/128x128/apps/lskat.png
/opt/trinity/share/icons/hicolor/64x64/apps/lskat.png
/opt/trinity/share/icons/hicolor/48x48/apps/lskat.png
/opt/trinity/share/icons/hicolor/32x32/apps/lskat.png
/opt/trinity/share/icons/hicolor/22x22/apps/lskat.png
/opt/trinity/share/icons/hicolor/16x16/apps/lskat.png
/opt/trinity/share/applications/tde/lskat.desktop
../icons/lskat.xpm /opt/trinity/share/pixmaps
../icons/lskat-16.xpm /opt/trinity/share/pixmaps
