#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up automatic login (Trinity)..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

if [ -f /root/etc/trinity/tdm/kdmrc ]; then
    # Configure KDM-Trinity autologin
    sed -i -r \
        -e "s/^#?AutoLoginEnable=.*\$/AutoLoginEnable=true/" \
        -e "s/^#?AutoLoginUser=.*\$/AutoLoginUser=$USERNAME/" \
        -e "s/^#?AutoLoginAgain=.*\$/AutoLoginAgain=true/" \
        /root/etc/trinity/tdm/kdmrc
fi

if [ -f /root/etc/trinity/tdm/tdmrc ]; then
    # Configure TDM-Trinity autologin
    sed -i -r \
        -e "s/^#?AutoLoginEnable=.*\$/AutoLoginEnable=true/" \
        -e "s/^#?AutoLoginUser=.*\$/AutoLoginUser=$USERNAME/" \
        -e "s/^#?AutoLoginAgain=.*\$/AutoLoginAgain=true/" \
        /root/etc/trinity/tdm/tdmrc
fi

log_end_msg
