/opt/trinity/share/icons/hicolor/128x128/apps/kpat.png
/opt/trinity/share/icons/hicolor/64x64/apps/kpat.png
/opt/trinity/share/icons/hicolor/48x48/apps/kpat.png
/opt/trinity/share/icons/hicolor/32x32/apps/kpat.png
/opt/trinity/share/icons/hicolor/22x22/apps/kpat.png
/opt/trinity/share/icons/hicolor/16x16/apps/kpat.png
/opt/trinity/share/apps/kpat/*
/opt/trinity/share/applications/tde/kpat.desktop
/opt/trinity/games/kpat
/opt/trinity/share/doc/tde/HTML/en/kpat/*
../icons/kpat.xpm /opt/trinity/share/pixmaps
../icons/kpat-16.xpm /opt/trinity/share/pixmaps
