/opt/trinity/share/apps/kshisen/*
/opt/trinity/share/config.kcfg/kshisen.kcfg
/opt/trinity/share/icons/hicolor/128x128/apps/kshisen.png
/opt/trinity/share/icons/hicolor/64x64/apps/kshisen.png
/opt/trinity/share/icons/hicolor/48x48/apps/kshisen.png
/opt/trinity/share/icons/hicolor/32x32/apps/kshisen.png
/opt/trinity/share/icons/hicolor/22x22/apps/kshisen.png
/opt/trinity/share/icons/hicolor/16x16/apps/kshisen.png
/opt/trinity/share/applications/tde/kshisen.desktop
/opt/trinity/games/kshisen
/opt/trinity/share/doc/tde/HTML/en/kshisen/*
../icons/kshisen.xpm /opt/trinity/share/pixmaps
../icons/kshisen-16.xpm /opt/trinity/share/pixmaps
