/opt/trinity/bin/akregator
/opt/trinity/lib/kde3/libakregatorpart.la
/opt/trinity/lib/kde3/libakregatorpart.so
/opt/trinity/lib/kde3/libakregator_mk4storage_plugin.la
/opt/trinity/lib/kde3/libakregator_mk4storage_plugin.so
/opt/trinity/lib/libakregatorprivate.la
/opt/trinity/lib/libakregatorprivate.so
/opt/trinity/share/applications/kde/akregator.desktop
/opt/trinity/share/apps/akregator
/opt/trinity/share/config.kcfg/akregator.kcfg
/opt/trinity/share/config.kcfg/mk4config.kcfg
/opt/trinity/share/doc/kde/HTML/en/akregator
/opt/trinity/share/icons/hicolor/128x128/apps/akregator.png
/opt/trinity/share/icons/crystalsvg/16x16/actions/rss_tag.png
/opt/trinity/share/icons/crystalsvg/22x22/actions/rss_tag.png
/opt/trinity/share/icons/crystalsvg/32x32/actions/rss_tag.png
/opt/trinity/share/icons/crystalsvg/48x48/actions/rss_tag.png
/opt/trinity/share/icons/crystalsvg/64x64/actions/rss_tag.png
/opt/trinity/share/icons/crystalsvg/16x16/apps/akregator_empty.png
/opt/trinity/share/icons/hicolor/16x16/apps/akregator.png
/opt/trinity/share/icons/hicolor/22x22/apps/akregator.png
/opt/trinity/share/icons/hicolor/32x32/apps/akregator.png
/opt/trinity/share/icons/hicolor/48x48/apps/akregator.png
/opt/trinity/share/icons/hicolor/64x64/apps/akregator.png
/opt/trinity/share/icons/hicolor/scalable/apps/akregator.svgz
/opt/trinity/share/services/akregator_mk4storage_plugin.desktop
/opt/trinity/share/services/akregator_part.desktop
/opt/trinity/share/services/feed.protocol
/opt/trinity/share/services/kontact/akregatorplugin*.desktop
/opt/trinity/share/servicetypes/akregator_plugin.desktop
../icons/akregator.xpm /opt/trinity/share/pixmaps
../icons/akregator-16.xpm /opt/trinity/share/pixmaps

