debian/tmp/opt/trinity/lib/libk3b.so.*
debian/tmp/opt/trinity/lib/libk3bdevice.so.*
debian/tmp/opt/trinity/lib/*.la
debian/tmp/opt/trinity/lib/trinity/libk3balsaoutputplugin.la
debian/tmp/opt/trinity/lib/trinity/libk3balsaoutputplugin.so
debian/tmp/opt/trinity/lib/trinity/libk3bartsoutputplugin.la
debian/tmp/opt/trinity/lib/trinity/libk3bartsoutputplugin.so
debian/tmp/opt/trinity/lib/trinity/libk3bexternalencoder.la
debian/tmp/opt/trinity/lib/trinity/libk3bexternalencoder.so
debian/tmp/opt/trinity/lib/trinity/libk3bflacdecoder.la
debian/tmp/opt/trinity/lib/trinity/libk3bflacdecoder.so


debian/tmp/opt/trinity/lib/trinity/libk3boggvorbisdecoder.la
debian/tmp/opt/trinity/lib/trinity/libk3boggvorbisdecoder.so
debian/tmp/opt/trinity/lib/trinity/libk3boggvorbisencoder.la
debian/tmp/opt/trinity/lib/trinity/libk3boggvorbisencoder.so
debian/tmp/opt/trinity/lib/trinity/libk3bsoxencoder.la
debian/tmp/opt/trinity/lib/trinity/libk3bsoxencoder.so
debian/tmp/opt/trinity/lib/trinity/libk3bwavedecoder.la
debian/tmp/opt/trinity/lib/trinity/libk3bwavedecoder.so
debian/tmp/opt/trinity/lib/trinity/libk3baudioprojectcddbplugin.so
debian/tmp/opt/trinity/lib/trinity/libk3baudioprojectcddbplugin.la
debian/tmp/opt/trinity/lib/trinity/libk3baudiometainforenamerplugin.so
debian/tmp/opt/trinity/lib/trinity/libk3baudiometainforenamerplugin.la
debian/tmp/opt/trinity/lib/trinity/kio_videodvd.so
debian/tmp/opt/trinity/lib/trinity/kio_videodvd.la
