debian/tmp/opt/trinity/bin/krdc
debian/tmp/opt/trinity/share/applications/tde/krdc.desktop
debian/tmp/opt/trinity/share/apps/konqueror/servicemenus/smb2rdc.desktop
debian/tmp/opt/trinity/share/apps/krdc/pics/close.png
debian/tmp/opt/trinity/share/apps/krdc/pics/iconify.png
debian/tmp/opt/trinity/share/apps/krdc/pics/pindown.png
debian/tmp/opt/trinity/share/apps/krdc/pics/pinup.png
debian/tmp/opt/trinity/share/apps/krdc/pics/pointcursor.png
debian/tmp/opt/trinity/share/apps/krdc/pics/pointcursormask.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/authentication.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/close.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/index.docbook
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/krdc_window.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/preferences_profilestab.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/preferences_rdpdefaultstab.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/preferences_vncdefaultstab.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/snapshot.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/snapshot_connectionspeed.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/snapshot_nobrowse.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/snapshot_vncentry.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/window_fullscreen.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/krdc/window_nofullscreen.png
debian/tmp/opt/trinity/share/icons/crystalsvg/32x32/apps/krdc.png
debian/tmp/opt/trinity/share/icons/crystalsvg/48x48/apps/krdc.png
debian/tmp/opt/trinity/share/services/rdp.protocol
debian/tmp/opt/trinity/share/services/vnc.protocol

debian/icons/krdc-16.xpm	/opt/trinity/share/pixmaps
debian/icons/krdc.xpm		/opt/trinity/share/pixmaps
