opt/trinity/bin/kbruch
/opt/trinity/share/apps/kbruch/kbruchui.rc
/opt/trinity/share/applications/kde/kbruch.desktop
/opt/trinity/share/config.kcfg/kbruch.kcfg
/opt/trinity/share/doc/tde/HTML/en/kbruch/*.bz2
/opt/trinity/share/doc/tde/HTML/en/kbruch/common
/opt/trinity/share/doc/tde/HTML/en/kbruch/*.docbook
/opt/trinity/share/doc/tde/HTML/en/kbruch/*.png
/opt/trinity/share/icons/hicolor/16x16/apps/kbruch.png
/opt/trinity/share/icons/hicolor/22x22/apps/kbruch.png
/opt/trinity/share/icons/hicolor/32x32/apps/kbruch.png
/opt/trinity/share/icons/hicolor/48x48/apps/kbruch.png
/opt/trinity/share/icons/hicolor/64x64/apps/kbruch.png
/opt/trinity/share/icons/hicolor/128x128/apps/kbruch.png
/opt/trinity/share/icons/hicolor/scalable/apps/kbruch.svgz
/opt/trinity/share/icons/crystalsvg/32x32/actions/kbruch_*.png
/opt/trinity/share/icons/crystalsvg/64x64/actions/kbruch_*.png
../icons/kbruch.xpm /opt/trinity/share/pixmaps
