.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KSENSORS 1 "May 02, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ksensors \- lm-sensors frontend for KDE 
.SH SYNOPSIS
.B ksensors
.RI "[ options ]"
.SH DESCRIPTION
.B KSensors
is a lm-sensors frontend for KDE for monitoring a motherboard.
It allows you to access information from temperature and fan
speed sensors.
.SH OPTIONS
A summary of options are included below.
.TP
.B \-\-nodock
Don't dock in KDE system tray.
.TP
.B \-\-splash
Show splash screen.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-help\-qt
Show Qt specific options
.TP
.B \-\-help\-kde
Show KDE specific options
.TP
.B \-\-help\-all
Show all options
.TP
.B \-\-author
Show author information
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-\-license
Show license information
.SH AUTHOR
.B KSensors
was written by Miguel Novas <michaell@teleline.es>.
.br
This manual page was written by Aurelien Jarno <aurel32@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
