debian/tmp/etc/trinity/kookarc
debian/tmp/opt/trinity/bin/kooka
debian/tmp/opt/trinity/share/applications/kde/kooka.desktop
debian/tmp/opt/trinity/share/apps/kooka/kookaui.rc
debian/tmp/opt/trinity/share/apps/kooka/pics/gocr.png
debian/tmp/opt/trinity/share/apps/kooka/pics/lockzoom.png
debian/tmp/opt/trinity/share/apps/kooka/pics/mirror-both.png
debian/tmp/opt/trinity/share/apps/kooka/pics/mirror-horiz.png
debian/tmp/opt/trinity/share/apps/kooka/pics/mirror-vert.png
debian/tmp/opt/trinity/share/apps/kooka/pics/newfromselect.png
debian/tmp/opt/trinity/share/apps/kooka/pics/ocr-select.png
debian/tmp/opt/trinity/share/apps/kooka/pics/ocr.png
debian/tmp/opt/trinity/share/apps/kooka/pics/ocrad.png
debian/tmp/opt/trinity/share/apps/kooka/pics/scaleorig.png
debian/tmp/opt/trinity/share/apps/kooka/pics/scaletoheight.png
debian/tmp/opt/trinity/share/apps/kooka/pics/scaletowidth.png
debian/tmp/opt/trinity/share/apps/kooka/pics/thumbviewtile.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/index.docbook
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/kooka_gocr.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/kooka_gocr_result.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/kooka_mainctrl.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/ocr-select.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/shortcut0.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/shortcut1.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/toolbar.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/toolbar1.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kooka/toolbar2.png

debian/icons/kooka.xpm		/opt/trinity/share/pixmaps
debian/icons/kooka-16.xpm	/opt/trinity/share/pixmaps
