.TH "makeqpf" "1" "3.0.3" "Troll Tech AS, Norway." ""
.SH "NAME"
.LP 
makeqpf \- Create qpf files from TTF and BDF files.
.SH "DESCRIPTION"
.LP 
Qt Prerendered Font (QPF) is a light\-weight non\-scalable
font format specific to Qt/Embedded.  makeqpf is a tool
that assists producing QPF files from TTF and BDF files.


.SH "SYNTAX"
qembed [ \fIgeneral\-files\fP ] <[ \fI\-\-images image\-files \fP]>
.br 

general\-files 
  These files can be any type of file. 
\-\-images image\-files 
  These files must be in image formats supported by Qt. 

.SH "FILES"
.LP 
\fI$(QTDIR)/etc/fonts/fontdir\fP 
.SH "AUTHORS"
.LP 
TrollTech <http://www.trolltech.com/>
