#! /usr/bin/env bash

filelist=$1

rm -f "$filelist"_* $filelist

touch $filelist

dir=.

find $dir -name "*.directory" -print | grep -v debian >> $filelist
find $dir -name "*.kdelnk" -print | grep -v debian >> $filelist
find $dir -name "*.desktop" -print | grep -v debian >> $filelist
find $dir -name "*.kimap" -print | grep -v debian >> $filelist
find $dir -name "*.themerc" -print | grep -v debian >> $filelist
find $dir -name "*.kcsrc" -print | grep -v debian >> $filelist
find $dir -name "*.setdlg" -print | grep -v debian >> $filelist
find $dir -name "index.theme" -print | grep -v debian >> $filelist
find $dir -name "eventsrc" -print | grep -v debian >> $filelist
find $dir -name "*.protocol" -print | grep -v debian >> $filelist

### TEMPORARY START: we do not have TDE modules
if true; then
find ./konqueror -name .svn -prune , -name "directory.*" -type f  2>/dev/null | grep -v debian >> $filelist
find ./kdesktop -name .svn -prune , -name "directory.*" -type f 2>/dev/null | grep -v debian >> $filelist 
find ./drkonqi -name "*rc" -print 2>/dev/null | grep -v debian >> $filelist
find ./kimgio -name \*.kimgio -print 2>/dev/null | grep -v debian >> $filelist
find ./noatun -name \*.plugin -print 2>/dev/null | grep -v debian >> $filelist
find ./noatun-plugins -name \*.plugin -print 2>/dev/null | grep -v debian >> $filelist
find ./amor/data -name \*rc -print 2>/dev/null | grep -v debian >> $filelist
find ./tdeprint -name \*.print -print 2>/dev/null | grep -v debian >> $filelist 
find . -name \*.kksrc -print 2>/dev/null | grep -v debian >> $filelist
find ./kopete -name \*.plugin -print 2>/dev/null | grep -v debian >> $filelist
find . -name \*.kdevtemplate -print 2>/dev/null | grep -v debian >> $filelist
fi
### TEMPORARY END: we do not have TDE modules

# Extract .directory files in template directories of KOffice
find . -name .directory|fgrep templates >> $filelist

sort -o $filelist -u $filelist
