.TH "KSTREAMRIPPER" "1" "Apr 26, 2004" "Michael Ablassmeier" "sound"
.SH "NAME"
kstreamripper \- TDE frontend for streamripper
.SH "SYNOPSIS"
.B kstreamripper [Qt\-options] [TDE\-options]
.SH "DESCRIPTION"
KStreamRipper is a small frontend for the streamripper command
line utility. Streamripper captures internet shoutcast radio streams
on your harddisk and splits them up in mp3 files. KStreamRipper helps
you with managing/ripping your preferred streams.

.SH "OPTIONS"
.IP "\fB\-\-help\fR" 
Show help about options
.IP "\fB\-\-help\-qt\fR" 
Show Qt specific options
.IP "\fB\-\-help\-tde\fR" 
Show TDE specific options
.IP "\fB\-\-help\-all\fR" 
Show all options
.IP "\fB\-\-author\fR"
Show author information
.IP "\fB\-v, \-\-version\fR"
Show version information
.IP "\fB\-\-license\fR"
Show license information
.IP "\fB\-\-\fR"
End of options
.SH "SEE ALSO"
streamripper(1)
.SH "AUTHOR"
2004 \- Created by Michael Ablassmeier (abi@grinser.de) for the Debian Project.
