#!/bin/bash

# BEGIN VERSIONS
VERSION=3.5.12.99
ARTS_VERSION=1.5.10
DBUS_TQT_VERSION=0.62
DBUS_1_TQT_VERSION=0.8.1
# END VERSIONS

createTarball()
{
cp -r $NAME $NAME-$VERSION
tar cjf $NAME-$VERSION.tar.bz2 $NAME-$VERSION
rm -rf $NAME-$VERSION
}

grabDepends()
{
svn export svn://anonsvn.kde.org/home/kde/branches/trinity/dependencies/$NAME
createTarball
rm -rf $NAME
echo "done"
}

grabMain()
{
svn export svn://anonsvn.kde.org/home/kde/branches/trinity/$NAME
createTarball
rm -rf $NAME
echo "done"
}

echo "I need to know what you want to generate a tarball for."
echo ""
echo "Version defaults to $VERSION. If you want to change it,"
echo "please pass it as a parameter to this script. There may"
echo "be other versions used, see the \"versions\" file."
echo ""
echo "Let's start off by dependencies, main, or apps."
echo "Which one?"
echo ""
echo "(1) dependencies"
echo "(2) main"
echo "(3) applications"
echo -e "> "
read SELECTION

if [ "$SELECTION" = "1" ]; then
	clear
	echo "Dependencies: Select what you want us to generate."
	echo "(1) libtqt4"
	echo "(2) libdbus-tqt-1-0"
	echo "(3) libdbus-1-tqt-0"
	echo "(4) arts"
	read CHOICE
	
	if [ "$CHOICE" = "1" ]; then NAME='tqtinterface';
	elif [ "$CHOICE" = "2" ]; then NAME='dbus-tqt' && VERSION=$DBUS_TQT_VERSION;
	elif [ "$CHOICE" = "3" ]; then NAME='dbus-1-tqt' && VERSION=$DBUS_1_TQT_VERSION;
	elif [ "$CHOICE" = "4" ]; then NAME='arts' && VERSION=$ARTS_VERSION;
	else
	echo "Invalid, bye." && exit 1
	fi
	grabDepends
elif [ "$SELECTION" = "2" ]; then
	clear
	echo "Main: Select what you want us to generate."
	echo "(1) tdelibs"
	echo "(2) tdebase"
	read CHOICE
	
	if [ "$CHOICE" = "1" ]; then NAME='kdelibs';
	elif [ "$CHOICE" = "2" ]; then NAME='kdebase';
	else
	echo "Invalid, bye." && exit 1
	fi
	grabMain
else
	echo "Invalid, bye." && exit 1
fi

