.TH RBKDEAPI 1 "Aug 2004" "K Desktop Environment" "Korundum KDE Ruby Bindings Manual"
.SH NAME
rbkdeapi \- A Korundum KDE Ruby Introspection Tool
.SH SYNOPSIS
.B rbkdeapi
[options] [<class>]
.SH DESCRIPTION
Rbkdeapi is a Korundum KDE Ruby Introspection Tool, similar to
javap(1).  Use it to find a list of method for a certain Korundum class.
.SH OPTIONS
.TP 
.B \-r <re>
Find all functions matching regular expression/keyword <re>
.TP
.B \-i
Perform a case insensitive search ( only meaningful in combination with -r )
.TP
.B \-p
Display also inherited methods.
.TP
.B \-v
Print QtRuby and Qt versions.
.TP
.B \-h
Print a help message.
.SH AUTHOR
Alexander Kellett
.SH SEE ALSO
rbqtapi(1)
