.TH KPOKER 6
.SH NAME
kpoker \- TDE video poker game
.SH SYNOPSIS
.B kpoker
.I [Qt-options] [TDE-options]
.SH DESCRIPTION
.B kpoker
is a TDE compliant clone of those highly addictive pocket video poker
games which are sometimes called ``Videopoker'' as well.
.so kdeopt.part
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/kpoker
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/kpoker').
