/opt/trinity/share/apps/katomic/*
/opt/trinity/share/icons/hicolor/16x16/apps/katomic.png
/opt/trinity/share/icons/hicolor/22x22/apps/katomic.png
/opt/trinity/share/icons/hicolor/32x32/apps/katomic.png
/opt/trinity/share/icons/hicolor/48x48/apps/katomic.png
/opt/trinity/share/icons/hicolor/64x64/apps/katomic.png
/opt/trinity/share/icons/hicolor/128x128/apps/katomic.png
/opt/trinity/share/applications/kde/katomic.desktop
/opt/trinity/games/katomic
/opt/trinity/share/doc/kde/HTML/en/katomic/*
../icons/katomic.xpm /opt/trinity/share/pixmaps
../icons/katomic-16.xpm /opt/trinity/share/pixmaps
