/etc/trinity/magic/kolf.magic
/opt/trinity/share/apps/kolf/*
/opt/trinity/games/kolf
/opt/trinity/share/applications/kde/kolf.desktop
/opt/trinity/share/doc/kde/HTML/en/kolf/*
/opt/trinity/share/icons/hicolor/16x16/apps/kolf.png
/opt/trinity/share/icons/hicolor/22x22/apps/kolf.png
/opt/trinity/share/icons/hicolor/32x32/apps/kolf.png
/opt/trinity/share/icons/hicolor/48x48/apps/kolf.png
/opt/trinity/share/icons/hicolor/64x64/apps/kolf.png
/opt/trinity/share/icons/hicolor/128x128/apps/kolf.png
/opt/trinity/share/mimelnk/application/x-kolf.desktop
/opt/trinity/share/mimelnk/application/x-kourse.desktop
/opt/trinity/lib/libkdeinit_kolf.so
/opt/trinity/lib/libkdeinit_kolf.la
/opt/trinity/lib/trinity/kolf.la
/opt/trinity/lib/trinity/kolf.so
/opt/trinity/lib/libkolf.la
/opt/trinity/lib/libkolf.so.1
/opt/trinity/lib/libkolf.so.1.2.0
../icons/kolf.xpm /opt/trinity/share/pixmaps
../icons/kolf-16.xpm /opt/trinity/share/pixmaps
