/opt/trinity/games/ktuberling
/opt/trinity/share/icons/hicolor/128x128/apps/ktuberling.png
/opt/trinity/share/icons/hicolor/64x64/apps/ktuberling.png
/opt/trinity/share/icons/hicolor/48x48/apps/ktuberling.png
/opt/trinity/share/icons/hicolor/32x32/apps/ktuberling.png
/opt/trinity/share/icons/hicolor/22x22/apps/ktuberling.png
/opt/trinity/share/icons/hicolor/16x16/apps/ktuberling.png
/opt/trinity/share/doc/tde/HTML/en/ktuberling/*
/opt/trinity/share/applications/kde/ktuberling.desktop
/opt/trinity/share/apps/ktuberling/*
/opt/trinity/share/mimelnk/application/x-tuberling.desktop
../icons/ktuberling.xpm /opt/trinity/share/pixmaps
../icons/ktuberling-16.xpm /opt/trinity/share/pixmaps
