/opt/trinity/games/kwin4
/opt/trinity/games/kwin4proc
/opt/trinity/share/apps/kwin4/*
/opt/trinity/share/config.kcfg/kwin4.kcfg
/opt/trinity/share/icons/hicolor/128x128/apps/kwin4.png
/opt/trinity/share/icons/hicolor/64x64/apps/kwin4.png
/opt/trinity/share/icons/hicolor/48x48/apps/kwin4.png
/opt/trinity/share/icons/hicolor/32x32/apps/kwin4.png
/opt/trinity/share/icons/hicolor/22x22/apps/kwin4.png
/opt/trinity/share/icons/hicolor/16x16/apps/kwin4.png
/opt/trinity/share/applications/kde/kwin4.desktop
/opt/trinity/share/doc/kde/HTML/en/kwin4/*
../icons/kwin4.xpm /opt/trinity/share/pixmaps
../icons/kwin4-16.xpm /opt/trinity/share/pixmaps
