.TH "createcw" "1" "3.0.3" "Troll Tech AS, Norway." ""
.SH "NAME"
.LP 
createcw \- custom widget description creater for Qt Designer
.SH "SYNTAX"
.LP 
createcw <\fIfilename.cw\fP>
.SH "DESCRIPTION"
.LP 
This small application makes it much easier to create
custom widget descriptions for the Qt Designer. Using
them you can use custom widgets in the Qt Designer
including their signals, slots and properties.
 
To do that normally you would have to enter all that
information in the custom widget dialog in the Qt
Designer for each widget. But this small tool can create
for you these description files for your custom widgets
which you then can simply import into the Qt Designer. So
you can use your custom widgets without any additional
work in your forms in the Qt Designer then.

To do that you have to modify the sourcecode (main.cpp) a
bit and recompile it afterwards. 

STEP1: Include header files of the widgets for which a
description should be created here. If you have a widget
which is defined in the file mycustomwidget.h in
/home/joedeveloper/src, write here 

#include "/home/joedeveloper/src/mycustomwidget.h"

STEP2: Instantiate all widgets for which a description
should be created here and add them to the list wl. If
your custom widget is e.g. called MyCustomWidget you
would write here

 Widget w;
 w.w = new MyCustomWidget( 0, 0 );
 w.include = "mycustomwidget.h";
 w.location = "global";
 wl.append( w );

After that compile the program, link it with your custom
widget (library or object file) and run it like this:

 (unix): ./createcw mywidgets.cw
 (win32): createcw mywidgets.cw

After that you can import this description file into the
Qt Designer using the Custom\-Widget Dialog (See
Tools\->Custom\->Edit Custom Widgets... in the Qt Designer)
and use these custom widget there in your forms.

.SH "AUTHORS"
.LP 
Troll Tech <http://www.trolltech.com/>
