.TH "mergetr" "1" "3.0.3" "Troll Tech AS, Norway." ""
.SH "NAME"
.LP 
mergetr \- Merge changes in translations
.SH "SYNTAX"
.LP 
mergetr myapp_de.po myapp.po

.SH "DESCRIPTION"
.LP 
When the texts in your program change as it is developed,
a the base .po file can be regenerated using findtr,
then mergetr can be used to merge the changes into the
other .po files: 

                mergetr myapp_de.po myapp.po
                mergetr myapp_fr.po myapp.po
                mergetr myapp_ja.po myapp.po


The translation team then edits the new .po files to
translate the new or changed texts. When texts change,
the old text is included in the .po file as a comment to
guide the new translation (no "fuzzy" matching is done).
.SH "AUTHORS"
.LP 
TrollTech <http://www.trolltech.com/>
