#! /bin/sh

set -e

case "$1" in

	remove)
		/usr/sbin/dpkg-statoverride --quiet --remove /usr/kde3/bin/klaptop_acpi_helper > /dev/null 2>&1 || true
		if [ -e /usr/kde3/bin/klaptop_acpi_helper ]; then
			chown root:root /usr/kde3/bin/klaptop_acpi_helper
			chmod 0755 /usr/kde3/bin/klaptop_acpi_helper
		fi
	;;

	upgrade|deconfigure)
	;;

	failed-upgrade)
	;;

	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
