debian/tmp/opt/trinity/bin/ktimer
debian/tmp/opt/trinity/share/applications/tde/ktimer.desktop
debian/tmp/opt/trinity/share/doc/tde/HTML/en/ktimer/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/ktimer/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/ktimer/index.docbook
debian/tmp/opt/trinity/share/icons/hicolor/128x128/apps/ktimer.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/ktimer.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/ktimer.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/ktimer.png

debian/icons/ktimer.xpm		/opt/trinity/share/pixmaps
debian/icons/ktimer-16.xpm	/opt/trinity/share/pixmaps
