#! /bin/sh

set -e

package_name=tdesudo-trinity

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    # remove old diversions if present
    divert=`dpkg-divert --listpackage "/usr/trinity/bin/kdesu"`
    if [ -n "$divert" ] && [ "$divert" = "kdesudo-trinity" ]; then
        dpkg-divert --remove --package kdesudo-trinity --rename /usr/trinity/bin/kdesu
    fi
    divert=`dpkg-divert --listpackage "/opt/trinity/bin/kdesu"`
    if [ -n "$divert" ] && [ "$divert" = "kdesudo-trinity" ]; then
        dpkg-divert --remove --package kdesudo-trinity --rename /opt/trinity/bin/kdesu
    fi

    # add new diversion
    dpkg-divert --package $package_name \
    --divert /opt/trinity/bin/tdesu.distrib \
    --rename /opt/trinity/bin/tdesu
    ;;

  upgrade)
    # remove old diversion if present
    divert=`dpkg-divert --listpackage "/usr/trinity/bin/tdesu"`
    if [ -n "$divert" ] && [ "$divert" = "$package_name" ]; then
        dpkg-divert --remove --package $package_name --rename "/usr/trinity/bin/tdesu"
    fi

    # add new diversion
    divert=`dpkg-divert --listpackage "/opt/trinity/bin/tdesu"`
    if [ -z "$divert" ]; then
        dpkg-divert --package $package_name \
                    --divert /opt/trinity/bin/tdesu.distrib \
                    --rename /opt/trinity/bin/tdesu
    fi
    ;;

  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
