etc/trinity/kstarsrc
opt/trinity/bin/kstars
/opt/trinity/include/kde/kstarsinterface.h
/opt/trinity/include/kde/simclockinterface.h
/opt/trinity/share/applications/kde/kstars.desktop
/opt/trinity/share/config.kcfg/kstars.kcfg
/opt/trinity/share/doc/kde/HTML/en/kstars/common
/opt/trinity/share/doc/kde/HTML/en/kstars/index.cache.bz2
/opt/trinity/share/doc/kde/HTML/en/kstars/*.docbook
/opt/trinity/share/doc/kde/HTML/en/kstars/*.png
/opt/trinity/share/icons/hicolor/16x16/apps/kstars.png
/opt/trinity/share/icons/hicolor/32x32/apps/kstars.png
/opt/trinity/share/icons/hicolor/48x48/apps/kstars.png
/opt/trinity/share/icons/hicolor/64x64/apps/kstars.png
/opt/trinity/share/icons/hicolor/128x128/apps/kstars.png
/opt/trinity/share/icons/hicolor/scalable/apps/kstars.svgz
../icons/kstars.xpm /opt/trinity/share/pixmaps
