debian/tmp/opt/trinity/bin/konversation
debian/tmp/opt/trinity/share/applications/kde/konversation.desktop
debian/tmp/opt/trinity/share/apps/kconf_update/*
debian/tmp/opt/trinity/share/apps/konversation/eventsrc
debian/tmp/opt/trinity/share/apps/konversation/konversationui.rc
debian/tmp/opt/trinity/share/apps/konversation/scripts/*
debian/tmp/opt/trinity/share/apps/konversation/themes/*
debian/tmp/opt/trinity/share/config.kcfg/konversation.kcfg
debian/tmp/opt/trinity/share/doc/kde/HTML/da/konversation/*
debian/tmp/opt/trinity/share/doc/kde/HTML/en/konversation/*
debian/tmp/opt/trinity/share/doc/kde/HTML/es/konversation/*
debian/tmp/opt/trinity/share/doc/kde/HTML/et/konversation/*
debian/tmp/opt/trinity/share/doc/kde/HTML/it/konversation/*
debian/tmp/opt/trinity/share/doc/kde/HTML/pt/konversation/*
debian/tmp/opt/trinity/share/doc/kde/HTML/ru/konversation/*
debian/tmp/opt/trinity/share/doc/kde/HTML/sv/konversation/*
debian/tmp/opt/trinity/share/icons/*
debian/tmp/opt/trinity/share/locale/*
debian/tmp/opt/trinity/share/services/konvirc.protocol
debian/tmp/opt/trinity/share/services/konvirc6.protocol

# Debian menu XPM icons
debian/*.xpm /opt/trinity/share/pixmaps

