debian/tmp/opt/kde3/include/tde/kjsembed/*
debian/tmp/opt/kde3/lib/libkjsembed.so
debian/tmp/opt/kde3/lib/libkjsembed.la

kjsembed/plugins/customobject_plugin.cpp		/opt/kde3/share/doc/libkjsembed-kde3-dev/plugin-examples/customobject/
kjsembed/plugins/customobject_plugin.h			/opt/kde3/share/doc/libkjsembed-kde3-dev/plugin-examples/customobject/
kjsembed/plugins/customobject_plugin.desktop		/opt/kde3/share/doc/libkjsembed-kde3-dev/plugin-examples/customobject/
kjsembed/plugins/customqobject_plugin.cpp		/opt/kde3/share/doc/libkjsembed-kde3-dev/plugin-examples/customqobject/
kjsembed/plugins/customqobject_plugin.h			/opt/kde3/share/doc/libkjsembed-kde3-dev/plugin-examples/customqobject/
kjsembed/plugins/customqobject_plugin.desktop		/opt/kde3/share/doc/libkjsembed-kde3-dev/plugin-examples/customqobject/

kjsembed/docs/embedding/simple-embed/	/opt/kde3/share/doc/libkjsembed-kde3-dev/embedding-examples/simple-embed/
