debian/tmp/opt/kde3/bin/rbqtsh
debian/tmp/opt/kde3/bin/rbqtapi
debian/tmp/opt/kde3/bin/rbuic
debian/tmp/opt/kde3/bin/qtrubyinit

debian/tmp/opt/kde3/lib/ruby/1.8/Qt/qtruby.rb
debian/tmp/opt/kde3/lib/ruby/1.8/Qt.rb

debian/tmp/opt/kde3/lib/ruby/1.8/*/qtruby.so*
debian/tmp/opt/kde3/lib/ruby/1.8/*/qtruby.la

debian/tmp/opt/kde3/lib/ruby/1.8/*/qui.so*
debian/tmp/opt/kde3/lib/ruby/1.8/*/qui.la

qtruby/ChangeLog /opt/kde3/share/doc/libqt0-ruby1.8
