opt/trinity/bin/keduca
opt/trinity/bin/keducabuilder
opt/trinity/lib/kde3/libkeducapart.la
opt/trinity/lib/kde3/libkeducapart.so
/opt/trinity/share/applications/kde/keduca.desktop
/opt/trinity/share/applications/kde/keducabuilder.desktop
/opt/trinity/share/apps/keduca
/opt/trinity/share/config.kcfg/keduca.kcfg
/opt/trinity/share/doc/kde/HTML/en/keduca/common
/opt/trinity/share/doc/kde/HTML/en/keduca/index.cache.bz2
/opt/trinity/share/doc/kde/HTML/en/keduca/*.docbook
/opt/trinity/share/doc/kde/HTML/en/keduca/*.png
/opt/trinity/share/icons/hicolor/16x16/apps/keduca.png
/opt/trinity/share/icons/hicolor/22x22/apps/keduca.png
/opt/trinity/share/icons/hicolor/32x32/apps/keduca.png
/opt/trinity/share/icons/hicolor/48x48/apps/keduca.png
/opt/trinity/share/icons/hicolor/64x64/apps/keduca.png
/opt/trinity/share/icons/hicolor/128x128/apps/keduca.png
/opt/trinity/share/mimelnk/application/x-edu.desktop
/opt/trinity/share/mimelnk/application/x-edugallery.desktop
/opt/trinity/share/services/keduca_part.desktop
../icons/keduca.xpm /opt/trinity/share/pixmaps
../keduca-shrinker opt/trinity/bin
