.TH QT: "1" "April 2007" "Qt: 3.3.7" "User Commands"
.SH NAME
kshowmail \- A powerful pop3 mail checker
.SH SYNOPSIS
.B kshowmail
[\fIQt-options\fR] [\fITDE-options\fR] [\fIoptions\fR] [\fIaccount\fR]
.SH DESCRIPTION
KShowmail can be used to show mails on a POP3 server without actually
downloading them. The headers or the complete mails can be viewed, and
unwanted mails can be deleted. An initial and an interval timer can be set to
check the mails periodical. KShowmail supports multiple accounts.
.SS "Generic options:"
.TP
\fB\-\-help\fR
Show help about options
.TP
\fB\-\-help\-qt\fR
Show Qt specific options
.TP
\fB\-\-help\-tde\fR
Show TDE specific options
.TP
\fB\-\-help\-all\fR
Show all options
.TP
\fB\-\-author\fR
Show author information
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information
.TP
\fB\-\-license\fR
Show license information
.TP
\fB\-\-\fR
End of options
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-refresh\fR
Refresh messages now
.TP
\fB\-c\fR, \fB\-\-config\fR
Launch configure dialog
.SS "Arguments:"
.TP
account
Select account
.PP
KDE: 3.5.6
KShowmail: 3.1.2
.SH "SEE ALSO"
The full documentation for
.B Qt:
is maintained as a Texinfo manual.  If the
.B info
and
.B Qt:
programs are properly installed at your site, the command
.IP
.B info Qt:
.PP
should give you access to the complete manual.
