debian/tmp/opt/trinity/share/doc/tde/HTML/en/tdevelop
#debian/tmp/opt/trinity/share/doc/tde/HTML/en/tdevelop-apidocs/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kde_app_devel/appwizard.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kde_app_devel/index.docbook
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kde_app_devel/kscribblefiles.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kde_app_devel/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kde_app_devel/common
