/opt/trinity/games/kbackgammon
/opt/trinity/share/applications/kde/kbackgammon.desktop
/opt/trinity/share/apps/kbackgammon/*
/opt/trinity/share/icons/hicolor/128x128/apps/kbackgammon.png
/opt/trinity/share/icons/hicolor/64x64/apps/kbackgammon.png
/opt/trinity/share/icons/hicolor/48x48/apps/kbackgammon.png
/opt/trinity/share/icons/hicolor/32x32/apps/kbackgammon.png
/opt/trinity/share/icons/hicolor/22x22/apps/kbackgammon.png
/opt/trinity/share/icons/hicolor/16x16/apps/kbackgammon.png
/opt/trinity/share/icons/hicolor/64x64/apps/kbackgammon_engine.png
/opt/trinity/share/icons/hicolor/48x48/apps/kbackgammon_engine.png
/opt/trinity/share/icons/hicolor/32x32/apps/kbackgammon_engine.png
/opt/trinity/share/icons/hicolor/16x16/apps/kbackgammon_engine.png
/opt/trinity/share/doc/tde/HTML/en/kbackgammon/*
../icons/kbackgammon.xpm /opt/trinity/share/pixmaps
../icons/kbackgammon-16.xpm /opt/trinity/share/pixmaps
