/opt/trinity/share/apps/kenolaba/*
/opt/trinity/share/icons/hicolor/16x16/apps/kenolaba.png
/opt/trinity/share/icons/hicolor/22x22/apps/kenolaba.png
/opt/trinity/share/icons/hicolor/32x32/apps/kenolaba.png
/opt/trinity/share/icons/hicolor/48x48/apps/kenolaba.png
/opt/trinity/share/icons/hicolor/64x64/apps/kenolaba.png
/opt/trinity/share/icons/hicolor/128x128/apps/kenolaba.png
/opt/trinity/share/applications/kde/kenolaba.desktop
/opt/trinity/games/kenolaba
/opt/trinity/share/doc/kde/HTML/en/kenolaba/*
../icons/kenolaba.xpm /opt/trinity/share/pixmaps
../icons/kenolaba-16.xpm /opt/trinity/share/pixmaps
