/opt/trinity/share/apps/kspaceduel/*
/opt/trinity/share/icons/hicolor/128x128/apps/kspaceduel.png
/opt/trinity/share/icons/hicolor/64x64/apps/kspaceduel.png
/opt/trinity/share/icons/hicolor/48x48/apps/kspaceduel.png
/opt/trinity/share/icons/hicolor/32x32/apps/kspaceduel.png
/opt/trinity/share/icons/hicolor/22x22/apps/kspaceduel.png
/opt/trinity/share/icons/hicolor/16x16/apps/kspaceduel.png
/opt/trinity/share/applications/kde/kspaceduel.desktop
/opt/trinity/games/kspaceduel
/opt/trinity/share/config.kcfg/kspaceduel.kcfg
/opt/trinity/share/doc/kde/HTML/en/kspaceduel/*
../icons/kspaceduel.xpm /opt/trinity/share/pixmaps
../icons/kspaceduel-16.xpm /opt/trinity/share/pixmaps
