debian/tmp/opt/trinity/bin/kaboodle
debian/tmp/opt/trinity/lib/trinity/libkaboodlepart.la
debian/tmp/opt/trinity/lib/trinity/libkaboodlepart.so
debian/tmp/opt/trinity/share/applications/tde/kaboodle.desktop
debian/tmp/opt/trinity/share/apps/kaboodle/icons/crystalsvg/16x16/actions/kaboodleloop.png
debian/tmp/opt/trinity/share/apps/kaboodle/icons/crystalsvg/22x22/actions/kaboodleloop.png
debian/tmp/opt/trinity/share/apps/kaboodle/kaboodlepartui.rc
debian/tmp/opt/trinity/share/apps/kaboodle/kaboodleui.rc
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kaboodle/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kaboodle/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kaboodle/index.docbook
debian/tmp/opt/trinity/share/icons/hicolor/128x128/apps/kaboodle.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kaboodle.png
debian/tmp/opt/trinity/share/icons/hicolor/22x22/apps/kaboodle.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kaboodle.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kaboodle.png
debian/tmp/opt/trinity/share/icons/hicolor/64x64/apps/kaboodle.png
debian/tmp/opt/trinity/share/services/kaboodle_component.desktop
debian/tmp/opt/trinity/share/services/kaboodleengine.desktop

debian/icons/kaboodle.xpm		/opt/trinity/share/pixmaps
debian/icons/kaboodle-16.xpm		/opt/trinity/share/pixmaps
