#! /bin/sh

set -e

package_name=kdesudo-kde3

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  configure)
	dpkg-divert --package $package_name --rename --remove \
                /usr/kde3/bin/kdesu || true
    ;;
  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
