/opt/trinity/share/apps/kbattleship/*
/opt/trinity/share/apps/zeroconf/_kbattleship._tcp
/opt/trinity/share/icons/hicolor/128x128/apps/kbattleship.png
/opt/trinity/share/icons/hicolor/64x64/apps/kbattleship.png
/opt/trinity/share/icons/hicolor/48x48/apps/kbattleship.png
/opt/trinity/share/icons/hicolor/32x32/apps/kbattleship.png
/opt/trinity/share/icons/hicolor/22x22/apps/kbattleship.png
/opt/trinity/share/icons/hicolor/16x16/apps/kbattleship.png
/opt/trinity/share/applications/kde/kbattleship.desktop
/opt/trinity/games/kbattleship
/opt/trinity/share/doc/kde/HTML/en/kbattleship/*
../icons/kbattleship.xpm /opt/trinity/share/pixmaps
../icons/kbattleship-16.xpm /opt/trinity/share/pixmaps
