/opt/trinity/games/ksame
/opt/trinity/share/doc/tde/HTML/en/ksame/*
/opt/trinity/share/icons/hicolor/128x128/apps/ksame.png
/opt/trinity/share/icons/hicolor/64x64/apps/ksame.png
/opt/trinity/share/icons/hicolor/48x48/apps/ksame.png
/opt/trinity/share/icons/hicolor/32x32/apps/ksame.png
/opt/trinity/share/icons/hicolor/22x22/apps/ksame.png
/opt/trinity/share/icons/hicolor/16x16/apps/ksame.png
/opt/trinity/share/apps/ksame/*
/opt/trinity/share/applications/kde/ksame.desktop
../icons/ksame.xpm /opt/trinity/share/pixmaps
../icons/ksame-16.xpm /opt/trinity/share/pixmaps
