/opt/trinity/share/apps/ksnake/*
/opt/trinity/share/config.kcfg/ksnake.kcfg
/opt/trinity/share/icons/hicolor/128x128/apps/ksnake.png
/opt/trinity/share/icons/hicolor/64x64/apps/ksnake.png
/opt/trinity/share/icons/hicolor/48x48/apps/ksnake.png
/opt/trinity/share/icons/hicolor/32x32/apps/ksnake.png
/opt/trinity/share/icons/hicolor/22x22/apps/ksnake.png
/opt/trinity/share/icons/hicolor/16x16/apps/ksnake.png
/opt/trinity/share/applications/kde/ksnake.desktop
/opt/trinity/games/ksnake
/opt/trinity/share/doc/kde/HTML/en/ksnake/*
../icons/ksnake.xpm /opt/trinity/share/pixmaps
../icons/ksnake-16.xpm /opt/trinity/share/pixmaps
