debian/tmp/opt/trinity/share/apps/amarok/*
debian/tmp/opt/trinity/share/apps/profiles/*
debian/tmp/opt/trinity/share/doc/*
debian/tmp/opt/trinity/share/icons/*
debian/tmp/opt/trinity/share/locale/*
debian/tmp/opt/trinity/share/config.kcfg/amarok.kcfg
debian/tmp/opt/trinity/share/services/amarok_void-engine_plugin.desktop
debian/tmp/opt/trinity/share/services/amarok_generic-mediadevice.desktop
debian/tmp/opt/trinity/share/services/amarok_ifp-mediadevice.desktop
debian/tmp/opt/trinity/share/services/amarok_ipod-mediadevice.desktop
debian/tmp/opt/trinity/share/services/amarok_njb-mediadevice.desktop
debian/tmp/opt/trinity/share/services/amarok_smb-device.desktop
debian/tmp/opt/trinity/share/services/amarok_massstorage-device.desktop
debian/tmp/opt/trinity/share/services/amarok_nfs-device.desktop
debian/tmp/opt/trinity/share/services/amarok_daap-mediadevice.desktop

#libkarma is not in MAIN yet
#debian/tmp/opt/trinity/share/services/amarok_riokarma-mediadevice.desktop

debian/tmp/opt/trinity/share/services/amarok_mtp-mediadevice.desktop
debian/tmp/opt/trinity/bin/amarok_proxy.rb
debian/tmp/opt/trinity/bin/amarok_daapserver.rb
debian/tmp/etc/*

