debian/tmp/opt/trinity/bin/superkaramba
debian/tmp/opt/trinity/share/applnk/Utilities/superkaramba.desktop
debian/tmp/opt/trinity/share/apps/superkaramba/superkarambaui.rc
debian/tmp/opt/trinity/share/doc/kde/HTML/en/superkaramba/common
debian/tmp/opt/trinity/share/doc/kde/HTML/en/superkaramba/index.cache.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/superkaramba/index.docbook
debian/tmp/opt/trinity/share/icons/crystalsvg/128x128/apps/superkaramba.png
debian/tmp/opt/trinity/share/icons/crystalsvg/128x128/mimetypes/superkaramba_theme.png
debian/tmp/opt/trinity/share/icons/crystalsvg/16x16/apps/superkaramba.png
debian/tmp/opt/trinity/share/icons/crystalsvg/16x16/mimetypes/superkaramba_theme.png
debian/tmp/opt/trinity/share/icons/crystalsvg/22x22/apps/superkaramba.png
debian/tmp/opt/trinity/share/icons/crystalsvg/22x22/mimetypes/superkaramba_theme.png
debian/tmp/opt/trinity/share/icons/crystalsvg/32x32/apps/superkaramba.png
debian/tmp/opt/trinity/share/icons/crystalsvg/32x32/mimetypes/superkaramba_theme.png
debian/tmp/opt/trinity/share/icons/crystalsvg/48x48/apps/superkaramba.png
debian/tmp/opt/trinity/share/icons/crystalsvg/48x48/mimetypes/superkaramba_theme.png
debian/tmp/opt/trinity/share/icons/crystalsvg/64x64/apps/superkaramba.png
debian/tmp/opt/trinity/share/icons/crystalsvg/64x64/mimetypes/superkaramba_theme.png
debian/tmp/opt/trinity/share/icons/crystalsvg/scalable/apps/superkaramba.svgz
debian/tmp/opt/trinity/share/icons/crystalsvg/scalable/mimetypes/superkaramba_theme.svgz
debian/tmp/opt/trinity/share/mimelnk/application/x-superkaramba.desktop

debian/icons/superkaramba.xpm		/opt/trinity/share/pixmaps
debian/icons/superkaramba-16.xpm	/opt/trinity/share/pixmaps
