.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KVPNC 1 "novembre 16, 2005"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kvpnc \- vpn clients frontend for TDE
.SH SYNOPSIS
.B kvpnc
.RI [ options ]
.br
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBkvpnc\fP is a TDE frontend for various vpn clients.
.br
It supports :
.br
 * Cisco-compatible VPN client (vpnc)
.br
 * IPSec (freeswan, openswan, racoon)
.br
 * Point-to-Point Tunneling Protocol (PPTP) client (pptp-linux)
.br
 * Virtual Private Network daemon (openvpn)
.SH OPTIONS
All TDE and Qt programs accept some common command\-line options.
.br
Kvpnc has no application\-specific options.
.PP
.TP
\fB\-\-help\fR
Show help about options
.TP
\fB\-\-help\-qt\fR
Show Qt specific options
.TP
\fB\-\-help\-tde\fR
Show TDE specific options
.TP
\fB\-\-help\-all\fR
Show all options
.TP
\fB\-\-author\fR
Show author information
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information
.TP
\fB\-\-license\fR
Show license information
.SH AUTHOR
kvpnc was written by Christoph Thielecke <crissi99@gmx.de>.
.PP
This manual page was written by Fathi Boudra <fboudra@free.fr>,
for the Debian project (but may be used by others).
