debian/tmp/opt/trinity/bin/khexedit
debian/tmp/opt/trinity/lib/kde3/libkbyteseditwidget.la
debian/tmp/opt/trinity/lib/kde3/libkbyteseditwidget.so
debian/tmp/opt/trinity/lib/kde3/libkhexedit2part.la
debian/tmp/opt/trinity/lib/kde3/libkhexedit2part.so
debian/tmp/opt/trinity/lib/libkhexeditcommon.so.0
debian/tmp/opt/trinity/lib/libkhexeditcommon.so.0.0.0
debian/tmp/opt/trinity/share/applications/kde/khexedit.desktop
debian/tmp/opt/trinity/share/apps/khexedit/khexeditui.rc
debian/tmp/opt/trinity/share/apps/khexedit/pics/hexdrag.png
debian/tmp/opt/trinity/share/apps/khexedit/pics/hexmask.png
debian/tmp/opt/trinity/share/apps/khexedit/pics/hexwrite.png
debian/tmp/opt/trinity/share/apps/khexedit2part/khexedit2partui.rc
debian/tmp/opt/trinity/share/doc/kde/HTML/en/khexedit/common
debian/tmp/opt/trinity/share/doc/kde/HTML/en/khexedit/index.cache.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/khexedit/index.docbook
debian/tmp/opt/trinity/share/doc/kde/HTML/en/khexedit/khexedit1.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/khexedit.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/khexedit.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/khexedit.png
debian/tmp/opt/trinity/share/services/kbyteseditwidget.desktop
debian/tmp/opt/trinity/share/services/khexedit2part.desktop

debian/icons/khexedit.xpm		/opt/trinity/share/pixmaps
debian/icons/khexedit-16.xpm		/opt/trinity/share/pixmaps
