.TH RBKDESH 1 "Aug 2004" "Trinity Desktop Environment" "Korundum TDE Ruby Bindings Manual"
.SH NAME
rbtdesh \- An Interactive Korundum Shell
.SH SYNOPSIS
.B rbtdesh
[options]
.SH DESCRIPTION
Rbtdesh is an interactive Korundum shell.  It shows a GUI dialog box
where you can enter Ruby code using the Korundum TDE Ruby bindings
library.
.SH OPTIONS
This program takes no options.
.SH AUTHOR
Germain Garand
Alexander Kellett
.SH SEE ALSO
rbqtsh(1)
