/opt/trinity/bin/korn
/opt/trinity/lib/kconf_update_bin/korn-3-4-config_change
/opt/trinity/share/applications/kde/KOrn.desktop
/opt/trinity/share/apps/kconf_update/korn-3-4-config_change.upd
/opt/trinity/share/apps/kconf_update/korn-3-5-metadata-update.pl
/opt/trinity/share/apps/kconf_update/korn-3-5-ssl-update.pl
/opt/trinity/share/apps/kconf_update/korn-3-5-update.upd
/opt/trinity/share/doc/kde/HTML/en/korn
/opt/trinity/share/icons/hicolor/16x16/apps/korn.png
/opt/trinity/share/icons/hicolor/32x32/apps/korn.png
/opt/trinity/share/icons/hicolor/48x48/apps/korn.png
../icons/korn.xpm /opt/trinity/share/pixmaps
../icons/korn-16.xpm /opt/trinity/share/pixmaps
