/opt/trinity/bin/ktnef
/opt/trinity/share/applications/kde/ktnef.desktop
/opt/trinity/share/apps/ktnef
/opt/trinity/share/doc/tde/HTML/en/ktnef
/opt/trinity/share/icons/hicolor/48x48/apps/ktnef.png
/opt/trinity/share/icons/locolor/16x16/apps/ktnef.png
/opt/trinity/share/icons/locolor/32x32/apps/ktnef.png
/opt/trinity/share/mimelnk/application/ms-tnef.desktop
../icons/ktnef.xpm /opt/trinity/share/pixmaps
../icons/ktnef-16.xpm /opt/trinity/share/pixmaps
