debian/tmp/opt/trinity/bin/rbqtsh
debian/tmp/opt/trinity/bin/rbqtapi
debian/tmp/opt/trinity/bin/rbuic
debian/tmp/opt/trinity/bin/qtrubyinit

debian/tmp/opt/trinity/lib/ruby/1.9.1/Qt/qtruby.rb
debian/tmp/opt/trinity/lib/ruby/1.9.1/Qt.rb

debian/tmp/opt/trinity/lib/ruby/1.9.1/*/qtruby.so*
debian/tmp/opt/trinity/lib/ruby/1.9.1/*/qtruby.la

debian/tmp/opt/trinity/lib/ruby/1.9.1/*/tqui.so*
debian/tmp/opt/trinity/lib/ruby/1.9.1/*/tqui.la

qtruby/ChangeLog /opt/trinity/share/doc/libqt0-ruby1.8
