debian/tmp/opt/trinity/bin/adddebug
debian/tmp/opt/trinity/bin/build-progress.sh
debian/tmp/opt/trinity/bin/cheatmake
debian/tmp/opt/trinity/bin/create_cvsignore
debian/tmp/opt/trinity/bin/create_makefile
debian/tmp/opt/trinity/bin/create_makefiles
debian/tmp/opt/trinity/bin/cvs-clean
debian/tmp/opt/trinity/bin/cvs2dist
debian/tmp/opt/trinity/bin/cvsbackport
debian/tmp/opt/trinity/bin/cvsblame
debian/tmp/opt/trinity/bin/cvscheck
debian/tmp/opt/trinity/bin/cvsforwardport
debian/tmp/opt/trinity/bin/cvslastchange
debian/tmp/opt/trinity/bin/cvslastlog
debian/tmp/opt/trinity/bin/cvsrevertlast
debian/tmp/opt/trinity/bin/cvsversion
debian/tmp/opt/trinity/bin/cxxmetric
debian/tmp/opt/trinity/bin/extend_dmalloc
debian/tmp/opt/trinity/bin/extractattr
debian/tmp/opt/trinity/bin/extractrc
debian/tmp/opt/trinity/bin/findmissingcrystal
debian/tmp/opt/trinity/bin/fixkdeincludes
debian/tmp/opt/trinity/bin/fixuifiles
debian/tmp/opt/trinity/bin/includemocs
debian/tmp/opt/trinity/bin/kde-build
debian/tmp/opt/trinity/bin/kdedoc
debian/tmp/opt/trinity/bin/kdekillall
debian/tmp/opt/trinity/bin/kdelnk2desktop.py
debian/tmp/opt/trinity/bin/kdemangen.pl
debian/tmp/opt/trinity/bin/makeobj
debian/tmp/opt/trinity/bin/noncvslist
debian/tmp/opt/trinity/bin/package_crystalsvg
debian/tmp/opt/trinity/bin/png2mng.pl
debian/tmp/opt/trinity/bin/pruneemptydirs
debian/tmp/opt/trinity/bin/qtdoc
debian/tmp/opt/trinity/bin/zonetab2pot.py
debian/tmp/opt/trinity/bin/svn2dist
debian/tmp/opt/trinity/bin/svnrevertlast
debian/tmp/opt/trinity/bin/svnforwardport
debian/tmp/opt/trinity/bin/nonsvnlist
debian/tmp/opt/trinity/bin/kdesvn-build
debian/tmp/opt/trinity/bin/svnlastlog
debian/tmp/opt/trinity/bin/svnversions
debian/tmp/opt/trinity/bin/create_svnignore
debian/tmp/opt/trinity/bin/svnlastchange
debian/tmp/opt/trinity/bin/colorsvn
debian/tmp/opt/trinity/bin/svnaddcurrentdir
debian/tmp/opt/trinity/bin/svnbackport
debian/tmp/opt/trinity/bin/svngettags
debian/tmp/opt/trinity/bin/svnchangesince
debian/tmp/opt/trinity/bin/svn-clean
debian/tmp/opt/trinity/share/apps/katepart/syntax/kdesvn-buildrc.xml
debian/tmp/opt/trinity/share/man/man1/cvsblame.1
debian/tmp/opt/trinity/share/man/man1/cvsversion.1
debian/tmp/opt/trinity/share/man/man1/kde-build.1
debian/tmp/opt/trinity/share/man/man1/includemocs.1
debian/tmp/opt/trinity/share/man/man1/noncvslist.1
debian/tmp/opt/trinity/share/man/man1/kdesvn-build.1
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kdesvn-build/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kdesvn-build/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kdesvn-build/index.docbook
scripts/kde-devel-gdb /opt/trinity/share/kdesdk-scripts
scripts/kde-devel-vim.vim /opt/trinity/share/kdesdk-scripts
scripts/kde-emacs/*.el /opt/trinity/share/emacs/site-lisp/kdesdk-scripts
scripts/kde.supp /opt/trinity/lib/valgrind
scripts/completions /opt/trinity/share/kdesdk-scripts

debian/desktop-i18n/createdesktop.pl /opt/trinity/lib/kubuntu-desktop-i18n/
debian/desktop-i18n/findfiles /opt/trinity/lib/kubuntu-desktop-i18n/
debian/desktop-i18n/msgsplit /opt/trinity/lib/kubuntu-desktop-i18n/

