debian/tmp/opt/trinity/bin/kuiviewer
debian/tmp/opt/trinity/lib/kde3/libkuiviewerpart.so
debian/tmp/opt/trinity/lib/kde3/libkuiviewerpart.la
debian/tmp/opt/trinity/lib/kde3/quithumbnail.so
debian/tmp/opt/trinity/lib/kde3/quithumbnail.la
debian/tmp/opt/trinity/share/applications/kde/kuiviewer.desktop
debian/tmp/opt/trinity/share/apps/kuiviewer/kuiviewerui.rc
debian/tmp/opt/trinity/share/apps/kuiviewerpart/kuiviewer_part.rc
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kuiviewer.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kuiviewer.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kuiviewer.png
debian/tmp/opt/trinity/share/icons/locolor/16x16/apps/kuiviewer.png
debian/tmp/opt/trinity/share/icons/locolor/32x32/apps/kuiviewer.png
debian/tmp/opt/trinity/share/services/designerthumbnail.desktop
debian/tmp/opt/trinity/share/services/kuiviewer_part.desktop
debian/icons/kuiviewer.xpm /opt/trinity/share/pixmaps
