#! /bin/sh -e

package_name=ksmserver-trinity

case "$1" in

    upgrade)
	# Remove old-style Plasma diversions
	dpkg-divert --package $package_name --rename --remove /usr/bin/plasma || true
	dpkg-divert --package $package_name --rename --remove /usr/bin/plasma-desktop || true
	mkdir -p /usr/share/autostart
    ;;

    install)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0
