.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KCPULOAD 1 "January 14, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kcpuload \- a CPU meter for Kicker
.SH SYNOPSIS
.B kcpuload
.RI "[ " generic-options " ]"
.SH DESCRIPTION
\fBKCPULoad\fP is a small program for Kicker (the KDE panel).  It
shows a recent history of CPU usage in the form of one or two
configurable diagrams in the system tray.
These diagrams have settings for colors and various different styles.
.PP
Note that it isn't the real system load that is shown, but the percent
used of the total CPU power, which is calculated from the number of
CPU ticks between each update.
.PP
If there is more than one CPU on the system, the combined CPU usage
from both can be shown, or you can choose to have one separate diagram
for each CPU.
.PP
Left click on a diagram to bring up a small information box which
will show the exact CPU usage in text form.
.PP
Note that using a slower update interval will give a more stable
and accurate diagram without flicker.
.SH OPTIONS
For a full summary of options, run \fIkcpuload \-\-help\fP.
.SH SEE ALSO
Full user documentation is available through the KDE Help Centre.
You can also enter the URL
\fIhelp:/kcpuload/\fP
directly into konqueror or you can run
`\fIkhelpcenter help:/kcpuload/\fP'
from the command-line.
.PP
If the KDE Help Centre is not installed then you can
read this documentation in HTML format from
\fI/usr/share/doc/tde/HTML/en/kcpuload/\fP.
.SH AUTHOR
KCPULoad was written by Markus Gustavsson <mighty@fragzone.se> and
Ben Burton <bab@debian.org>
