#! /bin/sh
set -e

#-- configure autologin
. /usr/share/debconf/confmodule

export LANG=C # avoid locale errors from perl
ROOT=/target
chroot=chroot
log='log-output -t trinity-livecd'

db_get passwd/username
USER="$RET"
db_get passwd/auto-login
if [ -n "$USER" ] && [ "$RET" = true ]; then
    if $chroot $ROOT [ -f /etc/trinity/kdm/kdmrc ]; then
        # Configure KDM autologin
        $log $chroot $ROOT sed -i$BACKUP -r \
            -e "s/^#?AutoLoginEnable=.*\$/AutoLoginEnable=true/" \
            -e "s/^#?AutoLoginUser=.*\$/AutoLoginUser=$USER/" \
            -e "s/^#?AutoLoginAgain=.*\$/AutoLoginAgain=true/" \
            /etc/trinity/kdm/kdmrc
    fi

    if $chroot $ROOT [ -f /etc/trinity/tdm/tdmrc ]; then
        # Configure TDM autologin
        $log $chroot $ROOT sed -i$BACKUP -r \
            -e "s/^#?AutoLoginEnable=.*\$/AutoLoginEnable=true/" \
            -e "s/^#?AutoLoginUser=.*\$/AutoLoginUser=$USER/" \
            -e "s/^#?AutoLoginAgain=.*\$/AutoLoginAgain=true/" \
            /etc/trinity/tdm/tdmrc
    fi
fi

#-- cleanup additional packages
packages=""
if [ -f "$ROOT/var/lib/dpkg/info/casper-trinity.list" ]; then
    packages="$packages casper-trinity"
fi
if [ -f "$ROOT/var/lib/dpkg/info/ubiquity-trinity.list" ]; then
    packages="$packages ubiquity-trinity"
fi
if [ -n "$packages" ]; then
    if [ -f "$ROOT/usr/bin/apt-get" ]; then
        $chroot $ROOT apt-get -y purge $packages
        $chroot $ROOT apt-get -y --purge autoremove
    else
        $chroot $ROOT dpkg -P $packages
    fi
fi

exit 0
