#! /bin/sh
#                               -*- Mode: Sh -*-
# Author: Frode M. Døving <frode@lnix.net> (C) 2007
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#

set -e

package_name=tdeio-umountwrapper-trinity

# make sure than the directories exist before running dpkg-divert
mkdir -p /opt/trinity/share/apps/konqueror/servicemenus/
mkdir -p /opt/trinity/share/apps/dolphin/servicemenus/
mkdir -p /opt/trinity/share/apps/d3lphin/servicemenus/

case "$1" in
  install)
    # remove old diversions if present
    divert=`dpkg-divert --listpackage "/opt/trinity/share/apps/konqueror/servicemenus/media_safelyremove.desktop"`
    if [ -n "$divert" ] && [ "$divert" = "kio-umountwrapper-trinity" ]; then
        dpkg-divert --package kio-umountwrapper-trinity --rename --remove /opt/trinity/share/apps/konqueror/servicemenus/media_safelyremove.desktop
    fi
    divert=`dpkg-divert --listpackage "/opt/trinity/share/apps/dolphin/servicemenus/media_safelyremove.desktop"`
    if [ -n "$divert" ] && [ "$divert" = "kio-umountwrapper-trinity" ]; then
        dpkg-divert --package kio-umountwrapper-trinity --rename --remove /opt/trinity/share/apps/dolphin/servicemenus/media_safelyremove.desktop
    fi
    divert=`dpkg-divert --listpackage "/opt/trinity/share/apps/d3lphin/servicemenus/media_safelyremove.desktop"`
    if [ -n "$divert" ] && [ "$divert" = "kio-umountwrapper-trinity" ]; then
        dpkg-divert --package kio-umountwrapper-trinity --rename --remove /opt/trinity/share/apps/d3lphin/servicemenus/media_safelyremove.desktop
    fi

    # add new diversions
    dpkg-divert --package $package_name \
    --divert /opt/trinity/share/apps/konqueror/servicemenus/media_safelyremove.desktop.distrib \
    --rename /opt/trinity/share/apps/konqueror/servicemenus/media_safelyremove.desktop

    dpkg-divert --package $package_name \
    --divert /opt/trinity/share/apps/dolphin/servicemenus/media_safelyremove.desktop.distrib \
    --rename /opt/trinity/share/apps/dolphin/servicemenus/media_safelyremove.desktop

    dpkg-divert --package $package_name \
    --divert /opt/trinity/share/apps/d3lphin/servicemenus/media_safelyremove.desktop.distrib \
    --rename /opt/trinity/share/apps/d3lphin/servicemenus/media_safelyremove.desktop

    ;;
  upgrade)
    divert=`dpkg-divert --listpackage "/opt/trinity/share/apps/konqueror/servicemenus/media_safelyremove.desktop"`
    if [ -z "$divert" ]; then
        dpkg-divert --package $package_name \
                    --divert /opt/trinity/share/apps/konqueror/servicemenus/media_safelyremove.desktop.distrib \
                    --rename /opt/trinity/share/apps/konqueror/servicemenus/media_safelyremove.desktop
    fi

    divert=`dpkg-divert --listpackage "/opt/trinity/share/apps/dolphin/servicemenus/media_safelyremove.desktop"`
    if [ -z "$divert" ]; then
        dpkg-divert --package $package_name \
                    --divert /opt/trinity/share/apps/dolphin/servicemenus/media_safelyremove.desktop.distrib \
                    --rename /opt/trinity/share/apps/dolphin/servicemenus/media_safelyremove.desktop
    fi

    divert=`dpkg-divert --listpackage "/opt/trinity/share/apps/d3lphin/servicemenus/media_safelyremove.desktop"`
    if [ -z "$divert" ]; then
        dpkg-divert --package $package_name \
                    --divert /opt/trinity/share/apps/d3lphin/servicemenus/media_safelyremove.desktop.distrib \
                    --rename /opt/trinity/share/apps/d3lphin/servicemenus/media_safelyremove.desktop
    fi

    exit 0
    ;;

  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0
     ;;
esac

#DEBHELPER#

exit 0
