debian/kivio.xpm opt/trinity/share/pixmaps
debian/tmp/opt/trinity/share/applications/kde/kivio.desktop
debian/tmp/opt/trinity/share/apps/kivio
debian/tmp/opt/trinity/share/apps/konqueror/servicemenus/kivio_konqi.desktop
debian/tmp/opt/trinity/share/config.kcfg/kivio.kcfg
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kivio/*.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kivio/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kivio/*.docbook
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kivio.png
debian/tmp/opt/trinity/share/icons/hicolor/22x22/apps/kivio.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kivio.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kivio.png
debian/tmp/opt/trinity/share/services/kivio*
