debian/tmp/opt/trinity/bin/kthesaurus
debian/tmp/opt/trinity/lib/trinity/kthesaurus.*
debian/tmp/opt/trinity/lib/trinity/libthesaurustool.la
debian/tmp/opt/trinity/lib/trinity/libthesaurustool.so
debian/tmp/opt/trinity/lib/libtdeinit_kthesaurus.so
debian/tmp/opt/trinity/share/applnk/Office/KThesaurus.desktop
debian/tmp/opt/trinity/share/apps/thesaurus
debian/tmp/opt/trinity/share/doc/kde/HTML/en/thesaurus/*.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/thesaurus/common
debian/tmp/opt/trinity/share/doc/kde/HTML/en/thesaurus/*.docbook
debian/tmp/opt/trinity/share/services/thesaurustool.desktop
debian/kthesaurus.xpm opt/trinity/share/pixmaps
