opt/trinity/bin/digi*
/opt/trinity/include/tde
opt/trinity/lib
/opt/trinity/share/apps/digikam
/opt/trinity/share/apps/konqueror/servicemenus/digikam*.desktop
/opt/trinity/share/applications/kde/digikam.desktop
/opt/trinity/share/icons/hicolor/*/apps/digikam.png
/opt/trinity/share/locale
/opt/trinity/share/servicetypes/digikamimageplugin.desktop
/opt/trinity/share/services
debian/xpm.d/digikam.xpm /opt/trinity/share/pixmaps/
debian/xpm.d/digikam-16.xpm /opt/trinity/share/pixmaps/
