debian/tmp/opt/trinity/lib/libqtjavasupport.la
debian/tmp/opt/trinity/lib/libqtjavasupport.so
debian/tmp/opt/trinity/lib/libqtjavasupport.so.1
debian/tmp/opt/trinity/lib/libqtjavasupport.so.1.0.0

debian/tmp/opt/trinity/lib/jni/libqtjava.la
debian/tmp/opt/trinity/lib/jni/libqtjava.so
debian/tmp/opt/trinity/lib/jni/libqtjava.so.1
debian/tmp/opt/trinity/lib/jni/libqtjava.so.1.0.0

qtjava/ChangeLog /opt/trinity/share/doc/libqt3-jni
