#! /bin/sh -e

case "$1" in

    upgrade)
	rm -f /etc/trinity/debian/kdm-update-menu.sh
	rm -f /etc/trinity/debian/kdm.options
	rm -f /etc/trinity/kdm/pixmaps/XFree86bw.xpm
	rm -f /etc/trinity/kdm/pixmaps/XFree86.xpm
	rm -f /etc/trinity/kdm/Xresources
	rm -f /etc/menu-methods/kdm
    ;;

    install)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0
