debian/tmp/etc/trinity/klipperrc
debian/tmp/opt/trinity/bin/klipper
debian/tmp/opt/trinity/lib/trinity/klipper.la
debian/tmp/opt/trinity/lib/trinity/klipper_panelapplet.la
debian/tmp/opt/trinity/lib/trinity/klipper_panelapplet.so
debian/tmp/opt/trinity/lib/trinity/klipper.so
debian/tmp/opt/trinity/lib/libkdeinit_klipper.so
debian/tmp/opt/trinity/share/applications/kde/klipper.desktop
debian/tmp/opt/trinity/share/apps/kconf_update/klipper-1-2.pl
debian/tmp/opt/trinity/share/apps/kconf_update/klipper-trinity1.sh
debian/tmp/opt/trinity/share/apps/kconf_update/klipperrc.upd
debian/tmp/opt/trinity/share/apps/kconf_update/klippershortcuts.upd
debian/tmp/opt/trinity/share/apps/kicker/applets/klipper.desktop
debian/tmp/opt/trinity/share/autostart/klipper.desktop
debian/tmp/opt/trinity/share/doc/kde/HTML/en/klipper/common
debian/tmp/opt/trinity/share/doc/kde/HTML/en/klipper/index.cache.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/klipper/index.docbook
debian/tmp/opt/trinity/share/doc/kde/HTML/en/klipper/screenshot.png
debian/tmp/opt/trinity/share/icons/hicolor/128x128/apps/klipper.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/klipper.png
debian/tmp/opt/trinity/share/icons/hicolor/22x22/apps/klipper.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/klipper.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/klipper.png
debian/tmp/opt/trinity/share/icons/hicolor/64x64/apps/klipper.png
debian/tmp/opt/trinity/share/icons/hicolor/scalable/apps/klipper.svgz

debian/icons/klipper.xpm		/opt/trinity/share/pixmaps
debian/icons/klipper-16.xpm		/opt/trinity/share/pixmaps
