debian/tmp/opt/trinity/lib/trinity/plugins/integration/libqtkde.la
debian/tmp/opt/trinity/lib/trinity/plugins/integration/libqtkde.so
debian/tmp/opt/trinity/lib/trinity/plugins/integration/libqtkde.so.0
debian/tmp/opt/trinity/lib/trinity/plugins/integration/libqtkde.so.0.0.0
debian/tmp/opt/trinity/share/services/kded/kdeintegration.desktop
debian/tmp/opt/trinity/lib/trinity/kded_kdeintegration.la
debian/tmp/opt/trinity/lib/trinity/kded_kdeintegration.so
