.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.TH ROSEGARDEN-LILIPONDVIEW 1 "10 February 2006"
i
.SH NAME

rosegardern-lilypondview - display a lilypond file in a postscript
viewer.

.SH SYNOPSIS

rosegarden-lilypondview [-g] [FILE].ly

.SH DESCRIPTION

This script takes a Lilypond file as input.  It creates a temporary
sandbox, runs Lilypond against the input file, then opens a PostScript
viewer against the results in order to provide a graphical, printable
preview.

This script is used internally by Rosegarden, as the backend for the File -> 
Export -> Preview Lilypond file feature.

.SH OPTIONS
.BR \-g " " Use graphical mode

.SH REQUIREMENTS

Working installation of Lilypond 2.0 or later KGhostView or KPDF or
XPDF or GhostView or GS XDialog or Konsole or RXVT or Xterm [for
graphical mode only]

.SH AUTHOR
Chris Cannam

.SH COPYRIGHT
2005-2006 Fervent Software.


