.TH PERLQT 1 "July 31, 2002"
.SH NAME
pqtsh \- PerlTQt Graphical shell
.SH SYNOPSIS
.B pqtsh

.SH DESCRIPTION
This manual page documents briefly the
.B pqtsh
command.
.PP
\fBpqtsh\fP is a graphical shell that can be used to test and experiment
with the PerlTQt api interactively. It is fairly self-explanatory and includes
an interactive example (Help -> Example).

For more information, please see the documentation on the PerlTQt website
http://perlqt.sourceforge.net/

.SH AUTHOR
This manual page was written by Peter Hawkins <peter@hawkins.emu.id.au>,
for the Debian GNU/Linux system (but may be used by others).
