/opt/trinity/bin/karm
/opt/trinity/lib/libkarm.so
/opt/trinity/lib/libkarm.so.0
/opt/trinity/lib/libkarm.so.0.0.0
/opt/trinity/lib/trinity/libkarmpart.la
/opt/trinity/lib/trinity/libkarmpart.so
/opt/trinity/share/applications/tde/karm.desktop
/opt/trinity/share/applnk/Utilities/karm.desktop
/opt/trinity/share/apps/karm
/opt/trinity/share/apps/karmpart
/opt/trinity/share/doc/tde/HTML/en/karm
/opt/trinity/share/icons/hicolor/128x128/apps/karm.png
/opt/trinity/share/icons/hicolor/16x16/apps/karm.png
/opt/trinity/share/icons/hicolor/22x22/apps/karm.png
/opt/trinity/share/icons/hicolor/32x32/apps/karm.png
/opt/trinity/share/icons/hicolor/48x48/apps/karm.png
/opt/trinity/share/icons/hicolor/64x64/apps/karm.png
/opt/trinity/share/services/karm_part.desktop
/opt/trinity/share/services/kontact/karmplugin.desktop
../icons/karm.xpm /opt/trinity/share/pixmaps
../icons/karm-16.xpm /opt/trinity/share/pixmaps
