debian/tmp/opt/trinity/include/kde/kprofilemethod.h
debian/tmp/opt/trinity/lib/trinity/kabcformat_kdeaccounts.la
debian/tmp/opt/trinity/lib/trinity/kabcformat_kdeaccounts.so
debian/tmp/opt/trinity/lib/trinity/plugins/styles/scheck.so
debian/tmp/opt/trinity/lib/trinity/plugins/styles/scheck.la
debian/tmp/opt/trinity/share/apps/kabc/formats/kdeaccountsplugin.desktop
debian/tmp/opt/trinity/share/apps/kstyle/themes/scheck.themerc
kdepalettes/kde_xpaintrc /opt/trinity/share/kdepalettes
kdepalettes/KDE_Gimp /opt/trinity/share/kdepalettes
kdepalettes/README /opt/trinity/share/kdepalettes

debian/tmp/opt/trinity/lib/libkstartperf.so.1.0.0
debian/tmp/opt/trinity/lib/libkstartperf.so.1
debian/tmp/opt/trinity/lib/libkstartperf.so
debian/tmp/opt/trinity/lib/libkstartperf.la
debian/tmp/opt/trinity/bin/kstartperf
