.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.TH ROSEGARDEN-PROJECT-PACKAGE 1 "10 February 2006"

.SH NAME

rosegarden-project-package - converts between Rosegarden (.rg) files
and Rosegarden Project (.rgp) files.

.SH SYNOPSIS

orosegarden-project-package [--quiet] [--pack] [--unpack] [--conftest] [FILE] [.rg|.rgp]

.SH OPTIONS
.BR \-\-quiet " " Be silent
.BR \-\-unpack " " Unpack .rgp file
.BR \-\-pack " " Pack .rg file plus associated external data files into .rgp file
.BR \-\-conftest " " Test environment for necessary installed components

.SH DESCRIPTION

This program converts between Rosegarden (.rg) files and Rosegarden
Project (.rgp) files.  It is primarily intended to be used internally and 
transparently by the Rosegarden application.

A Rosegarden file (.rg) is a single file (in gzipped XML format)
that defines a Rosegarden composition in terms of events, segments,
programs, plugin data, references to audio files, and so on.  Some
of these types of information depend on the presence of external
files such as the audio files or plugin preset data, without which
the file cannot be used.

A Rosegarden Project (.rgp) file is a bundle of files, including the
Rosegarden file itself, as well as any audio file or other external
data it requires, in compressed form.  A Rosegarden Project file is
intended to be portable and self-contained, but the Rosegarden
program itself does not (at the time of writing) understand these
files directly.

This program can take a Rosegarden file, examine it to find out
which other data files it uses, and pack it to create the
corresponding Rosegarden Project file.  Conversely, it can also take
a Rosegarden Project file and unpack it as a project directory for
use with Rosegarden.

.SH REQUIREMENTS

Working installation of Lilypond 2.0 or later KGhostView or KPDF or
XPDF or GhostView or GS XDialog or Konsole or RXVT or Xterm [for
graphical mode only]

.SH AUTHOR
Chris Cannam

.SH COPYRIGHT
2005-2006 Fervent Software.


