debian/tmp/opt/trinity/bin/kteatime
debian/tmp/opt/trinity/share/applications/kde/kteatime.desktop
debian/tmp/opt/trinity/share/apps/kteatime
debian/tmp/opt/trinity/share/doc/kde/HTML/en/kteatime/*.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/kteatime/*.docbook
debian/tmp/opt/trinity/share/doc/kde/HTML/en/kteatime/*.png
debian/tmp/opt/trinity/share/doc/kde/HTML/en/kteatime/common
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kteatime.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kteatime.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kteatime.png

debian/icons/kteatime.xpm	opt/trinity/share/pixmaps
