.TH RBQTAPI 1 "Aug 2004" "K Desktop Environment" "Qt Ruby Bindings Manual"
.SH NAME
rbqtapi \- A QtRuby Introspection Tool
.SH SYNOPSIS
.B rbqtapi
[options] [<class>]
.SH DESCRIPTION
Rbqtapi is a QtRuby Introspection Tool, similar to javap(1).  Use it
to find a list of method for a certain QtRuby class.
.SH OPTIONS
.TP 
.B \-r <re>
Find all functions matching regular expression/keyword <re>
.TP
.B \-i
Perform a case insensitive search ( only meaningful in combination with -r )
.TP
.B \-p
Display also inherited methods.
.TP
.B \-v
Print QtRuby and Qt versions.
.TP
.B \-h
Print a help message.
.SH AUTHOR
Alexander Kellett
.SH SEE ALSO
rbtdeapi(1)
