debian/tmp/opt/trinity/bin/kscd
debian/tmp/opt/trinity/bin/workman2cddb.pl
debian/tmp/opt/trinity/share/applications/tde/kscd.desktop
debian/tmp/opt/trinity/share/apps/konqueror/servicemenus/audiocd_play.desktop
debian/tmp/opt/trinity/share/apps/kscd/icons/crystalsvg/22x22/actions/cdsmall.png
debian/tmp/opt/trinity/share/apps/profiles/kscd.profile.xml
debian/tmp/opt/trinity/share/config.kcfg/kscd.kcfg
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/index.docbook
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscdannounc.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd11.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd12.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd13.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd14.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd16.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd18.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd19.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd2.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd3.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd5.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd6.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kscd/kscd9.png
debian/tmp/opt/trinity/share/icons/hicolor/128x128/apps/kscd.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kscd.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kscd.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kscd.png
debian/tmp/opt/trinity/share/icons/hicolor/64x64/apps/kscd.png
debian/tmp/opt/trinity/share/mimelnk/text/xmcd.desktop

debian/icons/kscd.xpm		/opt/trinity/share/pixmaps
debian/icons/kscd-16.xpm	/opt/trinity/share/pixmaps
