debian/tmp/opt/trinity/bin/kfloppy
debian/tmp/opt/trinity/share/applications/kde/KFloppy.desktop
debian/tmp/opt/trinity/share/apps/konqueror/servicemenus/floppy_format.desktop
debian/tmp/opt/trinity/share/doc/kde/HTML/en/kfloppy/common
debian/tmp/opt/trinity/share/doc/kde/HTML/en/kfloppy/index.cache.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/kfloppy/index.docbook
debian/tmp/opt/trinity/share/icons/hicolor/128x128/apps/kfloppy.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kfloppy.png
debian/tmp/opt/trinity/share/icons/hicolor/22x22/apps/kfloppy.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kfloppy.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kfloppy.png
debian/tmp/opt/trinity/share/icons/hicolor/64x64/apps/kfloppy.png

debian/icons/kfloppy.xpm		/opt/trinity/share/pixmaps
debian/icons/kfloppy-16.xpm		/opt/trinity/share/pixmaps
