.TH PERLQT 1 "July 31, 2002"
.SH NAME
puic \- Perl-QT User Interface Compiler
.SH SYNOPSIS
.B puic
.RI " [ " options " ] [ " mode " ] " <uifile.ui> " 


Generate implementation:

.B puic
.RI " [ " options " ] " <input.ui> " 


Generate image collection:

.B puic
.RI " [ " options " ] " -embed " " <project> " " <image1> " " ... "


Generate subclass implementation:

.B puic
.RI " [ " options " ] " -subclass " " <classname> " " <uifile.ui> "

.SH DESCRIPTION
This manual page documents briefly the
.B puic
command.
.PP
\fBpuic\fP is a program that generates a Perl package from a User Interface
file created with the Qt Designer package. This will generate the package
defined in  the UI file and a basic main package for testing purposes.

For more information, please see the documentation on the PerlQt website
http://perlqt.sourceforge.net/

.SH OPTIONS
A summary of options is included below.
.TP
.B \-o <output filename>
Specify the name of the output file. If no output file is specified, stdout
will be used.
.TP
.B \-p <indent>
Set the indent in spaces (0 to use a tab)
.TP
.B \-nofwd
Omit imports of custom widgets
.TP
.B \-tr <func>
Use func(...) rather than trUtf8(...) for i18n
.TP
.B \-x
Generate extra code to test the class.
.TP
.B \-version
Display version information.
.TP
.B \-help
Display usage information.

.SH AUTHOR
This manual page was written by Peter Hawkins <peter@hawkins.emu.id.au>,
for the Debian GNU/Linux system (but may be used by others).
