debian/icons/klinkstatus.xpm	/opt/trinity/share/pixmaps

debian/tmp/opt/trinity/bin/klinkstatus
debian/tmp/opt/trinity/lib/trinity/libklinkstatuspart.la
debian/tmp/opt/trinity/lib/trinity/libklinkstatuspart.so
debian/tmp/opt/trinity/share/applications/kde/klinkstatus.desktop
debian/tmp/opt/trinity/share/apps/klinkstatus
debian/tmp/opt/trinity/share/apps/klinkstatuspart
debian/tmp/opt/trinity/share/config.kcfg/klinkstatus.kcfg
debian/tmp/opt/trinity/share/doc/kde/HTML/en/klinkstatus/*.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/klinkstatus/common
debian/tmp/opt/trinity/share/doc/kde/HTML/en/klinkstatus/*.docbook
debian/tmp/opt/trinity/share/doc/kde/HTML/en/klinkstatus/*.png
debian/tmp/opt/trinity/share/icons/crystalsvg/16x16/actions/bug.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/klinkstatus.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/klinkstatus.png
debian/tmp/opt/trinity/share/icons/hicolor/22x22/apps/klinkstatus.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/klinkstatus.png
debian/tmp/opt/trinity/share/icons/hicolor/64x64/apps/klinkstatus.png
debian/tmp/opt/trinity/share/icons/hicolor/128x128/apps/klinkstatus.png
debian/tmp/opt/trinity/share/services/klinkstatus_part.desktop
