#!/bin/sh

set -e

case "$1" in
  upgrade) ;;
  remove|failed-upgrade|deconfigure)
    update-alternatives --remove moc "/usr/bin/moc-tqt3"
    update-alternatives --remove uic "/usr/bin/uic-tqt3"
    update-alternatives --remove lupdate "/usr/bin/lupdate-tqt3"
    update-alternatives --remove lrelease "/usr/bin/lrelease-tqt3"
    update-alternatives --remove qmake "/usr/bin/qmake-tqt3"
    ;;
esac

#DEBHELPER#
