
debian/tmp/opt/trinity/lib/trinity/kcm_kamera.la
debian/tmp/opt/trinity/lib/trinity/kcm_kamera.so
debian/tmp/opt/trinity/lib/trinity/tdeio_kamera.la
debian/tmp/opt/trinity/lib/trinity/tdeio_kamera.so
debian/tmp/opt/trinity/share/applications/tde/kamera.desktop
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kamera/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kamera/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kamera/index.docbook
debian/tmp/opt/trinity/share/doc/tde/HTML/en/tdeioslave/camera
debian/tmp/opt/trinity/share/icons/crystalsvg/16x16/actions/camera_test.png
debian/tmp/opt/trinity/share/icons/crystalsvg/16x16/apps/camera.png
debian/tmp/opt/trinity/share/icons/crystalsvg/16x16/devices/camera.png
debian/tmp/opt/trinity/share/icons/crystalsvg/22x22/devices/camera.png
debian/tmp/opt/trinity/share/icons/crystalsvg/22x22/places/camera.png
debian/tmp/opt/trinity/share/icons/crystalsvg/32x32/devices/camera.png
debian/tmp/opt/trinity/share/icons/crystalsvg/32x32/places/camera.png
debian/tmp/opt/trinity/share/services/camera.protocol
