Document: libr
Title: Debian libr Manual
Author: <insert document author here>
Abstract: This manual describes what libr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libr/libr.sgml.gz

Format: postscript
Files: /usr/share/doc/libr/libr.ps.gz

Format: text
Files: /usr/share/doc/libr/libr.text.gz

Format: HTML
Index: /usr/share/doc/libr/html/index.html
Files: /usr/share/doc/libr/html/*.html
