'\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH kdpkg 1 2008-07-03 "" ""
.SH NAME
kdpkg \- KDE frontend for dpkg
.SH SYNOPSIS
'nh
.fi
.ad l
\fBkdpkg\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
If you klick on a .deb file kdpkg starts automatically for installing it.
It works like gdebi with the difference that kdpkg is a KDE application
.SH COPYRIGHT
This manual page was written by Alexander Kopf
<\*(T<kopf\-alexander@gmx.de\*(T>> for the
Ubuntu system (but may be used by others).
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License,
Version 2 or any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public
License can be found in
\*(T<\fI/usr/share/common\-licenses/GPL\-2\fR\*(T>.
