.\" This file was written by Harald Sitter <apachelogger@ubuntu.com>
.TH ksquirrel-libs-pi32ppm 1 "Jan 2008" "Dmitry Baryshev" "Backend script used by KSquirrel"
.SH NAME
ksquirrel-libs-pi32ppm
\- backend script used by KSquirrel
.SH SYNOPSIS
ksquirrel-libs-pi32ppm
.SH DESCRIPTION
Backend script used by KSquirrel
 Homepage: http://ksquirrel.sourceforge.net
.SH AUTHORS
.nf
Dmitry Baryshev <ksquirrel@tut.by>
.br
.SH OTHER
.nf
This manual page was written by Harald Sitter <apachelogger@ubuntu.com> for the Kubuntu
system (but may be used by others).
.br
