#!/usr/bin/perl -w

use Shell qw(mv cp mkdir rm) ;
use File::Find;
use Cwd;

$origPwd = `pwd`;
chomp $origPwd;


if (@ARGV && $ARGV[0] eq 'cleanup') {

if (-d "debian/tmp/usr/share/config") {
	if (! -d "debian/tmp/$tde_confdir") {
	  system("mv debian/tmp/usr/share/config debian/tmp/$tde_confdir");
	}
}
system("rm -f `find debian/ -name \".anchors\"`");
system("chmod 755 debian/*preinst debian/*postinst");

exit;
}

$TQTDIR="/usr/share/tqt3";
$tde_prefix="/opt/trinity";
$tde_htmldir="$tde_prefix/share/doc/kde/HTML";
$tde_icondir="$tde_prefix/share/icons";
$tde_sounddir="$tde_prefix/share/sounds";
$tde_datadir="$tde_prefix/share/apps";
$tde_locale="$tde_prefix/share/locale";
$tde_confdir="/etc/tde2";
$tde_cgidir="$tde_prefix/lib/cgi-bin";
$tde_appsdir="$tde_prefix/share/applnk";
$tde_mimedir="$tde_prefix/share/mimelnk";
$tde_wallpaperdir="$tde_prefix/share/wallpapers";
$tde_bindir="$tde_prefix/bin";
$tde_servicesdir="$tde_prefix/share/services";
$tde_servicetypesdir="$tde_prefix/share/servicetypes";
$tde_includedir="$tde_prefix/include/tde";
$tde_libdir="$tde_prefix/lib";
$tde_moduledir="$tde_prefix/lib/tde";
$mandir="$tde_prefix/share/man"; 
$infodir="$tde_prefix/share/info";
$IDL="$tde_bindir/cuteidl";
$DCOPIDL="$tde_bindir/dcopidl";
$DCOPIDL2CPP="$tde_bindir/dcopidl2cpp";
$KDB2HTML="$tde_bindir/kdb2html";
$MCOPIDL="$tde_bindir/mcopidl";
$ARTSCCONFIG="$tde_bindir/artsc-config";

if (@ARGV && $ARGV[0] eq 'echodirs') {
  print STDOUT "export tde_htmldir=$tde_htmldir\n";
  print STDOUT "export tde_appsdir=$tde_appsdir\n";
  print STDOUT "export tde_icondir=$tde_icondir\n";
  print STDOUT "export tde_sounddir=$tde_sounddir\n";
  print STDOUT "export tde_datadir=$tde_datadir\n";
  print STDOUT "export tde_cgidir=$tde_cgidir\n";
  print STDOUT "export tde_locale=$tde_locale\n";
  print STDOUT "export tde_confdir=$tde_confdir\n";
  print STDOUT "export tde_mimedir=$tde_mimedir\n";
  print STDOUT "export tde_wallpaperdir=$tde_wallpaperdir\n";
  print STDOUT "export tde_bindir=$tde_bindir\n";
  print STDOUT "export tde_servicesdir=$tde_servicesdir\n";
  print STDOUT "export tde_servicetypesdir=$tde_servicetypesdir\n";
  print STDOUT "export tde_includedir=$tde_includedir\n";
  print STDOUT "export tde_libdir=$tde_libdir\n";
  print STDOUT "export tde_moduledir=$tde_moduledir\n";
  print STDOUT "export mandir=$mandir\n";
  print STDOUT "export infodir=$infodir\n";
  print STDOUT "export TQTDIR=$TQTDIR\n";
  print STDOUT "export tde_prefix=$tde_prefix\n";
  print STDOUT "export INSTALL_DATA=install -p -c -m 644\n";
  print STDOUT "export IDL=$IDL\n";
  print STDOUT "export DCOPIDL=$DCOPIDL\n";
  print STDOUT "export DCOPIDL2CPP=$DCOPIDL2CPP\n";
  print STDOUT "export KDB2HTML=$KDB2HTML\n";
  print STDOUT "export MCOPIDL=$MCOPIDL\n";
  print STDOUT "export ARTSCCONFIG=$ARTSCCONFIG\n";
  print STDOUT "configtde=--disable-debug --disable-rpath --prefix=\$(tde_prefix) --libexecdir=\$(tde_bindir) --libdir=\$(tde_libdir) --includedir=\$(tde_includedir) --with-qt-includes=/usr/include/qt --mandir=\$(mandir) --infodir=\$(infodir)\n";
  print STDOUT "configtdevelop=--disable-debug --enable-docbase --enable-kdoc2 --disable-rpath --libdir=\$(tde_libdir) --includedir=\$(tde_includedir) --with-qt-includes=/usr/include/qt --mandir=\$(mandir) --with-tdelibsdoc-dir=/usr/share/doc/tdelibs3-doc/html\n";
  print STDOUT "configtdepim=--disable-debug --with-extra-includes=/usr/include/libpisock --enable-shared --disable-rpath --libdir=\$(tde_libdir) --includedir=\$(tde_includedir) --prefix=\$(tde_prefix) --libexecdir=\$(tde_bindir) --with-qt-includes=/usr/include/qt --mandir=\$(mandir) --infodir=\$(infodir)\n";
  exit
}

