debian/tmp/etc/trinity/ktalkdrc
debian/tmp/opt/trinity/bin/ktalkdlg
debian/tmp/opt/trinity/bin/mail.local
debian/tmp/opt/trinity/lib/trinity/kcm_ktalkd.la
debian/tmp/opt/trinity/lib/trinity/kcm_ktalkd.so
debian/tmp/opt/trinity/share/applications/kde/kcmktalkd.desktop
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kcontrol/kcmtalkd/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kcontrol/kcmtalkd/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kcontrol/kcmtalkd/index.docbook
debian/tmp/opt/trinity/share/doc/tde/HTML/en/ktalkd/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/ktalkd/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/ktalkd/index.docbook
debian/tmp/opt/trinity/share/icons/crystalsvg/128x128/apps/ktalkd.png
debian/tmp/opt/trinity/share/icons/crystalsvg/16x16/apps/ktalkd.png
debian/tmp/opt/trinity/share/icons/crystalsvg/22x22/apps/ktalkd.png
debian/tmp/opt/trinity/share/icons/crystalsvg/32x32/apps/ktalkd.png
debian/tmp/opt/trinity/share/icons/crystalsvg/48x48/apps/ktalkd.png
debian/tmp/opt/trinity/share/sounds/ktalkd.wav

debian/tmp/opt/trinity/bin/ktalkd	opt/trinity/sbin/
