debian/tmp/opt/trinity/lib/trinity/kcm_lanbrowser.la
debian/tmp/opt/trinity/lib/trinity/kcm_lanbrowser.so
debian/tmp/opt/trinity/lib/trinity/kio_lan.la
debian/tmp/opt/trinity/lib/trinity/kio_lan.so
debian/tmp/opt/trinity/share/applnk/.hidden/kcmkiolan.desktop
debian/tmp/opt/trinity/share/applnk/.hidden/kcmlisa.desktop
debian/tmp/opt/trinity/share/applnk/.hidden/kcmreslisa.desktop
debian/tmp/opt/trinity/share/apps/konqsidebartng/virtual_folders/services/lisa.desktop
debian/tmp/opt/trinity/share/apps/konqueror/dirtree/remote/lan.desktop
debian/tmp/opt/trinity/share/apps/lisa/README
debian/tmp/opt/trinity/share/apps/remoteview/lan.desktop
debian/tmp/opt/trinity/share/doc/kde/HTML/en/kcontrol/lanbrowser/common
debian/tmp/opt/trinity/share/doc/kde/HTML/en/kcontrol/lanbrowser/index.cache.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/kcontrol/lanbrowser/index.docbook
debian/tmp/opt/trinity/share/doc/kde/HTML/en/lisa/common
debian/tmp/opt/trinity/share/doc/kde/HTML/en/lisa/index.cache.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/lisa/index.docbook
debian/tmp/opt/trinity/share/services/lan.protocol
debian/tmp/opt/trinity/share/services/rlan.protocol

debian/lisarc		opt/trinity/etc/
debian/tmp/opt/trinity/bin/lisa		opt/trinity/sbin/
debian/tmp/opt/trinity/bin/reslisa	opt/trinity/sbin/
