/opt/trinity/bin/konsolekalendar
/opt/trinity/share/applications/kde/konsolekalendar.desktop
/opt/trinity/share/doc/tde/HTML/en/konsolekalendar/common
/opt/trinity/share/doc/tde/HTML/en/konsolekalendar/index.cache.bz2
/opt/trinity/share/doc/tde/HTML/en/konsolekalendar/index.docbook
/opt/trinity/share/icons/crystalsvg/16x16/apps/konsolekalendar.png
/opt/trinity/share/icons/crystalsvg/22x22/apps/konsolekalendar.png
/opt/trinity/share/icons/crystalsvg/32x32/apps/konsolekalendar.png
