#! /bin/sh -e

package_name=knetworkconf-trinity

divert_remove()
 {
    divert=`dpkg-divert --listpackage "$1"`
    if [ -n "$divert" ] && [ "$divert" = "LOCAL" ]; then
        dpkg-divert --remove --local --rename "$1"
    fi
    if [ -n "$divert" ] && [ "$divert" = "$package_name" ]; then
        dpkg-divert --remove --package $package_name --rename "$1"
    fi
 }

case "$1" in

    configure)
	divert_remove /usr/share/icons/hicolor/16x16/apps/knetworkconf.png
	divert_remove /usr/share/icons/hicolor/22x22/apps/knetworkconf.png
	divert_remove /usr/share/icons/hicolor/32x32/apps/knetworkconf.png
	divert_remove /usr/share/icons/hicolor/22x22/actions/network_connected_lan_knc.png
	divert_remove /usr/share/icons/hicolor/22x22/actions/network_disconnected_lan.png
	divert_remove /usr/share/icons/hicolor/22x22/actions/network_disconnected_wlan.png
	divert_remove /usr/share/icons/hicolor/22x22/actions/network_traffic_wlan.png
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0
