debian/tmp/opt/trinity/bin/kuser
debian/tmp/opt/trinity/share/applications/kde/kuser.desktop
debian/tmp/opt/trinity/share/apps/kuser/icons/crystalsvg/22x22/actions/add_group.png
debian/tmp/opt/trinity/share/apps/kuser/icons/crystalsvg/22x22/actions/add_user.png
debian/tmp/opt/trinity/share/apps/kuser/icons/crystalsvg/22x22/actions/delete_group.png
debian/tmp/opt/trinity/share/apps/kuser/icons/crystalsvg/22x22/actions/delete_user.png
debian/tmp/opt/trinity/share/apps/kuser/icons/crystalsvg/22x22/actions/edit_group.png
debian/tmp/opt/trinity/share/apps/kuser/icons/crystalsvg/22x22/actions/edit_user.png
debian/tmp/opt/trinity/share/apps/kuser/kuserui.rc
debian/tmp/opt/trinity/share/apps/kuser/pics/group.png
debian/tmp/opt/trinity/share/apps/kuser/pics/user.png
debian/tmp/opt/trinity/share/config.kcfg/kuser.kcfg
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kuser/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kuser/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kuser/index.docbook
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kuser/kuser.png
debian/tmp/opt/trinity/share/icons/hicolor/128x128/apps/kuser.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kuser.png
debian/tmp/opt/trinity/share/icons/hicolor/22x22/apps/kuser.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kuser.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kuser.png
debian/tmp/opt/trinity/share/icons/hicolor/64x64/apps/kuser.png

debian/icons/kuser.xpm		/opt/trinity/share/pixmaps
debian/icons/kuser-16.xpm	/opt/trinity/share/pixmaps
