debian/tmp/opt/trinity/bin/kwifimanager
debian/tmp/opt/trinity/lib/trinity/kcm_wifi.la
debian/tmp/opt/trinity/lib/trinity/kcm_wifi.so
debian/tmp/opt/trinity/lib/libkwireless.la
debian/tmp/opt/trinity/lib/libkwireless.so
debian/tmp/opt/trinity/share/applications/tde/kcmwifi.desktop
debian/tmp/opt/trinity/share/applications/tde/kwifimanager.desktop
debian/tmp/opt/trinity/share/apps/kicker/applets/kwireless.desktop
debian/tmp/opt/trinity/share/apps/kwifimanager/kwifimanagerui.rc
debian/tmp/opt/trinity/share/apps/kwifimanager/locations/DE_BW_Karlsruhe_University.loc
debian/tmp/opt/trinity/share/apps/kwifimanager/locations/NOWHERE.loc
debian/tmp/opt/trinity/share/apps/kwifimanager/pics/ad_hoc.png
debian/tmp/opt/trinity/share/apps/kwifimanager/pics/all_alone.png
debian/tmp/opt/trinity/share/apps/kwifimanager/pics/ap_connect.png
debian/tmp/opt/trinity/share/apps/kwifimanager/pics/excellent.png
debian/tmp/opt/trinity/share/apps/kwifimanager/pics/good.png
debian/tmp/opt/trinity/share/apps/kwifimanager/pics/marginal.png
debian/tmp/opt/trinity/share/apps/kwifimanager/pics/no_card.png
debian/tmp/opt/trinity/share/apps/kwifimanager/pics/offline.png
debian/tmp/opt/trinity/share/apps/kwifimanager/pics/oor_down.png
debian/tmp/opt/trinity/share/apps/kwifimanager/pics/oor_minimum.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kwifimanager/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kwifimanager/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kwifimanager/index.docbook
debian/tmp/opt/trinity/share/icons/hicolor/128x128/apps/kwifimanager.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kwifimanager.png
debian/tmp/opt/trinity/share/icons/hicolor/22x22/apps/kwifimanager.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kwifimanager.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kwifimanager.png
debian/tmp/opt/trinity/share/icons/hicolor/64x64/apps/kwifimanager.png
debian/tmp/opt/trinity/share/icons/hicolor/scalable/apps/kwifimanager.svgz

debian/icons/kwifimanager-16.xpm	/opt/trinity/share/pixmaps
debian/icons/kwifimanager.xpm		/opt/trinity/share/pixmaps
