#! /bin/sh

set -e

package_name=tdepowersave-trinity

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    # remove obsolete divert for acpid
    divert=`dpkg-divert --listpackage "/etc/acpi/powerbtn.sh"`
    if [ -n "$divert" ] && [ "$divert" = "LOCAL" ]; then
        dpkg-divert --remove --local --rename "/etc/acpi/powerbtn.sh"
    fi

    # create new divert for acpi-support-base
    dpkg-divert --package $package_name --rename /usr/share/acpi-support/policy-funcs
    ;;
  upgrade)
    # remove obsolete divert acpid
    divert=`dpkg-divert --listpackage "/etc/acpi/powerbtn.sh"`
    if [ -n "$divert" ]; then
        if [ "$divert" = "LOCAL" ]; then
            dpkg-divert --remove --local --rename "/etc/acpi/powerbtn.sh"
        fi
        if [ "$divert" = $package_name ]; then
            dpkg-divert --remove --package $package_name --rename "/etc/acpi/powerbtn.sh"
        fi
    fi

    # create new divert for acpi-support-base
    divert=`dpkg-divert --listpackage "/usr/share/acpi-support/policy-funcs"`
    if [ -z "$divert" ]; then
        dpkg-divert --package $package_name --rename /usr/share/acpi-support/policy-funcs
    fi
    ;;
  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

#DEBHELPER#

exit 0
