.TH "findtr" "1" "3.0.3" "Troll Tech AS, Norway." ""
.SH "NAME"
.LP 
findtr \- Extracts information about text to be translated
.SH "SYNTAX"
.LP 
findtr *.cpp *.h >myapp.po
.SH "DESCRIPTION"
.LP 

Extracts information about text to be translated. It
recognizes the tr() constructs described above and
produces a file in ".po" format, a simple text format
that your translation team will copy and edit. For
example, the base .po file might be myapp.po and
translated versions of the file would then be
myapp_de.po, myapp_fr.po, and myapp_ja.po for
translations in German, French and Japanese respectively.

  findtr *.cpp *.h >myapp.po
  copy myapp.po myapp_de.po
  edit myapp_de.po
.SH "AUTHORS"
.LP 
TrollTech <http://www.trolltech.com/>
