#! /bin/sh -e

case "$1" in

    configure)
	dpkg-divert --remove /usr/share/autostart/konqy_preload.desktop
        dpkg-divert --remove /usr/share/icons/hicolor/128x128/apps/konqueror.png
        dpkg-divert --remove /usr/share/icons/hicolor/16x16/apps/konqueror.png
        dpkg-divert --remove /usr/share/icons/hicolor/22x22/apps/konqueror.png
        dpkg-divert --remove /usr/share/icons/hicolor/32x32/apps/konqueror.png
        dpkg-divert --remove /usr/share/icons/hicolor/48x48/apps/konqueror.png
        dpkg-divert --remove /usr/share/icons/hicolor/64x64/apps/konqueror.png
        dpkg-divert --remove /usr/share/icons/hicolor/scalable/apps/konqueror.svgz
    ;;

    install)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0
