debian/tmp/opt/trinity/bin/kpager
debian/tmp/opt/trinity/share/applications/tde/kpager.desktop
debian/tmp/opt/trinity/share/applnk/Utilities/kpager.desktop
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kpager/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kpager/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kpager/index.docbook
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kpager/screenshot.png
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kpager/settings.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kpager.png
debian/tmp/opt/trinity/share/icons/hicolor/22x22/apps/kpager.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kpager.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kpager.png

debian/icons/kpager.xpm		/opt/trinity/share/pixmaps
debian/icons/kpager-16.xpm	/opt/trinity/share/pixmaps
