debian/tmp/opt/trinity/bin/ktip
debian/tmp/opt/trinity/share/applications/tde/ktip.desktop
debian/tmp/opt/trinity/share/applnk/Toys/ktip.desktop
debian/tmp/opt/trinity/share/apps/kdewizard/pics/wizard_small.png
debian/tmp/opt/trinity/share/apps/kdewizard/tips
debian/tmp/opt/trinity/share/autostart/ktip.desktop
debian/tmp/opt/trinity/share/icons/hicolor/128x128/apps/ktip.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/ktip.png
debian/tmp/opt/trinity/share/icons/hicolor/22x22/apps/ktip.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/ktip.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/ktip.png
debian/tmp/opt/trinity/share/icons/hicolor/64x64/apps/ktip.png
debian/tmp/opt/trinity/share/icons/hicolor/scalable/apps/ktip.svgz

debian/icons/ktip.xpm		/opt/trinity/share/pixmaps
debian/icons/ktip-16.xpm	/opt/trinity/share/pixmaps
