debian/tmp/opt/trinity/bin/kcharselect
debian/tmp/opt/trinity/lib/trinity/kcharselect_panelapplet.la
debian/tmp/opt/trinity/lib/trinity/kcharselect_panelapplet.so
debian/tmp/opt/trinity/share/applications/tde/KCharSelect.desktop
debian/tmp/opt/trinity/share/apps/kcharselect/kcharselectui.rc
debian/tmp/opt/trinity/share/apps/tdeconf_update/kcharselect.upd
debian/tmp/opt/trinity/share/apps/kicker/applets/kcharselectapplet.desktop
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kcharselect/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kcharselect/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kcharselect/index.docbook
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kcharselect.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kcharselect.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/kcharselect.png

debian/icons/kcharselect.xpm		/opt/trinity/share/pixmaps
debian/icons/kcharselect-16.xpm		/opt/trinity/share/pixmaps
