debian/tmp/opt/trinity/bin/kmousetool
debian/tmp/opt/trinity/share/applnk/Applications/kmousetool.desktop
debian/tmp/opt/trinity/share/apps/kmousetool/icons/hicolor/16x16/actions/kmousetool_off.png
debian/tmp/opt/trinity/share/apps/kmousetool/icons/hicolor/16x16/actions/kmousetool_on.png
debian/tmp/opt/trinity/share/apps/kmousetool/icons/hicolor/16x16/apps/kmousetool.png
debian/tmp/opt/trinity/share/apps/kmousetool/icons/hicolor/32x32/actions/kmousetool_off.png
debian/tmp/opt/trinity/share/apps/kmousetool/icons/hicolor/32x32/actions/kmousetool_on.png
debian/tmp/opt/trinity/share/apps/kmousetool/icons/hicolor/32x32/apps/kmousetool.png
debian/tmp/opt/trinity/share/apps/kmousetool/sounds/mousetool_tap.wav
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmousetool/common
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmousetool/index.cache.bz2
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmousetool/index.docbook
debian/tmp/opt/trinity/share/doc/tde/HTML/en/kmousetool/man-kmousetool.1.docbook
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/kmousetool.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/kmousetool.png

debian/icons/kmousetool.xpm		/opt/trinity/share/pixmaps
debian/icons/kmousetool-16.xpm		/opt/trinity/share/pixmaps
