.TH KDEVPRJ2KDEVELOP 1
.SH NAME
kdevprj2tdevelop \- KDevelop 2.x project converter
.SH SYNOPSIS
.B kdevprj2tdevelop
.I file
.SH DESCRIPTION
.B kdevprj2tdevelop
is a tool for converting KDevelop 2.x projects (*.kdevprj) to the
format used by TDevelop 3.x (*.tdevelop).
.SH PROGRAM OPTIONS
.TP
.B file
KDevelop 2.x project to convert.
