/opt/trinity/bin/knode
/opt/trinity/lib/kde3/kcm_knode.la
/opt/trinity/lib/kde3/kcm_knode.so
/opt/trinity/lib/kde3/libknodepart.la
/opt/trinity/lib/kde3/libknodepart.so
/opt/trinity/lib/libknodecommon.la
/opt/trinity/lib/libknodecommon.so
/opt/trinity/lib/libknodecommon.so.3
/opt/trinity/lib/libknodecommon.so.3.0.0
/opt/trinity/share/applications/kde/KNode.desktop
/opt/trinity/share/apps/knode
/opt/trinity/share/doc/kde/HTML/en/knode
/opt/trinity/share/icons/hicolor/128x128/apps/knode.png
/opt/trinity/share/icons/hicolor/128x128/apps/knode2.png
/opt/trinity/share/icons/hicolor/16x16/apps/knode.png
/opt/trinity/share/icons/hicolor/16x16/apps/knode2.png
/opt/trinity/share/icons/hicolor/32x32/apps/knode.png
/opt/trinity/share/icons/hicolor/32x32/apps/knode2.png
/opt/trinity/share/icons/hicolor/48x48/apps/knode.png
/opt/trinity/share/icons/hicolor/48x48/apps/knode2.png
/opt/trinity/share/icons/hicolor/64x64/apps/knode.png
/opt/trinity/share/icons/hicolor/64x64/apps/knode2.png
/opt/trinity/share/services/knewsservice.protocol
/opt/trinity/share/services/knode_config_*.desktop
/opt/trinity/share/services/kontact/knodeplugin.desktop
../icons/knode.xpm /opt/trinity/share/pixmaps
../icons/knode-16.xpm /opt/trinity/share/pixmaps
