.\"                                      Hey, EMACS: -*- nroff -*-
.TH KNOWIT 1 "Aug 24, 2006"
.SH NAME
knowit \- Tool for managing notes for KDE
.SH SYNOPSIS
.B knowit
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B knowit
command.
.PP
\fBKnowIt\fP is a tool for managing notes which are organized in
tree-like hierarchy. It is similar to TuxCards,
but KDE-based (it requires KDE 3).
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-\-help
Show help about options
.TP
.B \-\-help-qt
Show Qt specific options
.TP
.B \-\-help-kde
Show KDE specific options
.TP
.B \-\-help-all
Show all options
.TP
.B \-\-author
Show author information
.TP
.B \-v, \-\-version
Show version information
.TP
.B \-\-license
Show license information
.TP
.B \-\-
End of options
.TP
.br
.SH AUTHOR
knowit was written by Micha Rudolf
.PP
This manual page was written by Lorenzo Villani <arbiter@arbiterlab.net>,
for the Ubuntu project (but may be used by others).
