opt/trinity/bin/kalzium
/opt/trinity/share/applications/tde/kalzium.desktop
/opt/trinity/share/config.kcfg/kalzium.kcfg
/opt/trinity/share/doc/tde/HTML/en/kalzium/common
/opt/trinity/share/doc/tde/HTML/en/kalzium/index.cache.bz2
/opt/trinity/share/doc/tde/HTML/en/kalzium/*.docbook
/opt/trinity/share/doc/tde/HTML/en/kalzium/*.png
/opt/trinity/share/icons/hicolor/16x16/apps/kalzium.png
/opt/trinity/share/icons/hicolor/22x22/apps/kalzium.png
/opt/trinity/share/icons/hicolor/32x32/apps/kalzium.png
/opt/trinity/share/icons/hicolor/48x48/apps/kalzium.png
/opt/trinity/share/icons/hicolor/64x64/apps/kalzium.png
/opt/trinity/share/icons/hicolor/128x128/apps/kalzium.png
/opt/trinity/share/icons/hicolor/scalable/apps/kalzium.svgz
../icons/kalzium.xpm /opt/trinity/share/pixmaps
