opt/trinity/bin/ktouch
/opt/trinity/share/applications/kde/ktouch.desktop
/opt/trinity/share/apps/ktouch
/opt/trinity/share/config.kcfg/ktouch.kcfg
/opt/trinity/share/doc/tde/HTML/en/ktouch/common
/opt/trinity/share/doc/tde/HTML/en/ktouch/index.cache.bz2
/opt/trinity/share/doc/tde/HTML/en/ktouch/*.docbook
/opt/trinity/share/doc/tde/HTML/en/ktouch/*.png
/opt/trinity/share/icons/hicolor/16x16/apps/ktouch.png
/opt/trinity/share/icons/hicolor/22x22/apps/ktouch.png
/opt/trinity/share/icons/hicolor/32x32/apps/ktouch.png
/opt/trinity/share/icons/hicolor/48x48/apps/ktouch.png
/opt/trinity/share/icons/hicolor/128x128/apps/ktouch.png
/opt/trinity/share/icons/hicolor/scalable/apps/ktouch.svgz
../icons/ktouch.xpm /opt/trinity/share/pixmaps
