.TH RBTDEAPI 1 "Aug 2004" "Trinity Desktop Environment" "Korundum TDE Ruby Bindings Manual"
.SH NAME
rbtdeapi \- A Korundum TDE Ruby Introspection Tool
.SH SYNOPSIS
.B rbtdeapi
[options] [<class>]
.SH DESCRIPTION
Rbtdeapi is a Korundum TDE Ruby Introspection Tool, similar to
javap(1).  Use it to find a list of method for a certain Korundum class.
.SH OPTIONS
.TP 
.B \-r <re>
Find all functions matching regular expression/keyword <re>
.TP
.B \-i
Perform a case insensitive search ( only meaningful in combination with -r )
.TP
.B \-p
Display also inherited methods.
.TP
.B \-v
Print QtRuby and Qt versions.
.TP
.B \-h
Print a help message.
.SH AUTHOR
Alexander Kellett
.SH SEE ALSO
rbqtapi(1)
