debian/tmp/opt/trinity/bin/ksig
debian/tmp/opt/trinity/share/applications/kde/ksig.desktop
debian/tmp/opt/trinity/share/apps/ksig/ksigui.rc
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/ksig.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/ksig.png
debian/icons/ksig.xpm /opt/trinity/share/pixmaps
debian/tmp/opt/trinity/share/doc/kde/HTML/en/ksig/common
debian/tmp/opt/trinity/share/doc/kde/HTML/en/ksig/index.cache.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/ksig/index.docbook
debian/tmp/opt/trinity/share/doc/kde/HTML/en/ksig/screenshot.png
