debian/tmp/opt/trinity/bin/noatunsynaescope.bin
debian/tmp/opt/trinity/bin/noatuntippecanoe.bin
debian/tmp/opt/trinity/bin/noatuntyler.bin
debian/tmp/opt/trinity/lib/kde3/noatunalsaplayer.la
debian/tmp/opt/trinity/lib/kde3/noatunalsaplayer.so
debian/tmp/opt/trinity/lib/kde3/noatunblurscope.la
debian/tmp/opt/trinity/lib/kde3/noatunblurscope.so
debian/tmp/opt/trinity/lib/kde3/noatuncharlatan.la
debian/tmp/opt/trinity/lib/kde3/noatuncharlatan.so
debian/tmp/opt/trinity/lib/kde3/noatundub.la
debian/tmp/opt/trinity/lib/kde3/noatundub.so
debian/tmp/opt/trinity/lib/kde3/noatun_ffrs.la
debian/tmp/opt/trinity/lib/kde3/noatun_ffrs.so
debian/tmp/opt/trinity/lib/kde3/noatunluckytag.la
debian/tmp/opt/trinity/lib/kde3/noatunluckytag.so
debian/tmp/opt/trinity/lib/kde3/noatunlyrics.la
debian/tmp/opt/trinity/lib/kde3/noatunlyrics.so
debian/tmp/opt/trinity/lib/kde3/noatunmadness.la
debian/tmp/opt/trinity/lib/kde3/noatunmadness.so
debian/tmp/opt/trinity/lib/kde3/noatun_oblique.la
debian/tmp/opt/trinity/lib/kde3/noatun_oblique.so
debian/tmp/opt/trinity/lib/kde3/noatunpitchablespeed.la
debian/tmp/opt/trinity/lib/kde3/noatunpitchablespeed.so
debian/tmp/opt/trinity/lib/kde3/noatunsynaescope.la
debian/tmp/opt/trinity/lib/kde3/noatunsynaescope.so
debian/tmp/opt/trinity/lib/kde3/noatuntippecanoe.la
debian/tmp/opt/trinity/lib/kde3/noatuntippecanoe.so
debian/tmp/opt/trinity/lib/kde3/noatuntyler.la
debian/tmp/opt/trinity/lib/kde3/noatuntyler.so
debian/tmp/opt/trinity/lib/kde3/noatunwakeup.la
debian/tmp/opt/trinity/lib/kde3/noatunwakeup.so
debian/tmp/opt/trinity/lib/kde3/noatunwavecapture.la
debian/tmp/opt/trinity/lib/kde3/noatunwavecapture.so
debian/tmp/opt/trinity/share/apps/noatun/alsaplayerui.plugin
debian/tmp/opt/trinity/share/apps/noatun/blurscope.plugin
debian/tmp/opt/trinity/share/apps/noatun/charlatanui.plugin
debian/tmp/opt/trinity/share/apps/noatun/dub.plugin
debian/tmp/opt/trinity/share/apps/noatun/ffrs.plugin
debian/tmp/opt/trinity/share/apps/noatun/luckytag.plugin
debian/tmp/opt/trinity/share/apps/noatun/lyrics.plugin
debian/tmp/opt/trinity/share/apps/noatun/lyricsui.rc
debian/tmp/opt/trinity/share/apps/noatun/madness.plugin
debian/tmp/opt/trinity/share/apps/noatun/obliqueui.rc
debian/tmp/opt/trinity/share/apps/noatun/oblique.plugin
debian/tmp/opt/trinity/share/apps/noatun/oblique/schemas/standard
debian/tmp/opt/trinity/share/apps/noatun/pitchablespeed.plugin
debian/tmp/opt/trinity/share/apps/noatun/synaescope.plugin
debian/tmp/opt/trinity/share/apps/noatun/tippecanoe.plugin
debian/tmp/opt/trinity/share/apps/noatun/tyler.plugin
debian/tmp/opt/trinity/share/apps/noatun/tylerstates
debian/tmp/opt/trinity/share/apps/noatun/wakeup.plugin
debian/tmp/opt/trinity/share/apps/noatun/wavecapture.plugin
debian/tmp/opt/trinity/share/icons/crystalsvg/16x16/apps/synaescope.png
noatun-plugins/dub/AUTHORS /opt/trinity/share/doc/noatun-plugins/dub
noatun-plugins/dub/BUGS /opt/trinity/share/doc/noatun-plugins/dub
noatun-plugins/dub/ChangeLog /opt/trinity/share/doc/noatun-plugins/dub
noatun-plugins/dub/design.txt /opt/trinity/share/doc/noatun-plugins/dub
noatun-plugins/dub/NEWS /opt/trinity/share/doc/noatun-plugins/dub
noatun-plugins/dub/README /opt/trinity/share/doc/noatun-plugins/dub
noatun-plugins/dub/TODO /opt/trinity/share/doc/noatun-plugins/dub
noatun-plugins/lyrics/TODO /opt/trinity/share/doc/noatun-plugins/lyrics
noatun-plugins/tyler/AUTHORS /opt/trinity/share/doc/noatun-plugins/tyler
noatun-plugins/tyler/README /opt/trinity/share/doc/noatun-plugins/tyler
