/opt/trinity/share/icons/hicolor/128x128/apps/kmines.png
/opt/trinity/share/icons/hicolor/64x64/apps/kmines.png
/opt/trinity/share/icons/hicolor/48x48/apps/kmines.png
/opt/trinity/share/icons/hicolor/32x32/apps/kmines.png
/opt/trinity/share/icons/hicolor/22x22/apps/kmines.png
/opt/trinity/share/icons/hicolor/16x16/apps/kmines.png
/opt/trinity/share/applications/tde/kmines.desktop
/opt/trinity/share/apps/kmines/*
/opt/trinity/games/kmines
/opt/trinity/share/doc/tde/HTML/en/kmines/*
../icons/kmines.xpm /opt/trinity/share/pixmaps
../icons/kmines-16.xpm /opt/trinity/share/pixmaps
