#! /bin/sh -e

package_name=konqueror-trinity

divert_remove()
 {
    divert=`dpkg-divert --listpackage "$1"`
    if [ -n "$divert" ] && [ "$divert" = "LOCAL" ]; then
        dpkg-divert --remove --local --rename "$1"
    fi
    if [ -n "$divert" ] && [ "$divert" = "$package_name" ]; then
        dpkg-divert --remove --package $package_name --rename "$1"
    fi
 }

case "$1" in

    configure)
        divert_remove /usr/share/autostart/konqy_preload.desktop
        divert_remove /usr/share/icons/hicolor/128x128/apps/konqueror.png
        divert_remove /usr/share/icons/hicolor/16x16/apps/konqueror.png
        divert_remove /usr/share/icons/hicolor/22x22/apps/konqueror.png
        divert_remove /usr/share/icons/hicolor/32x32/apps/konqueror.png
        divert_remove /usr/share/icons/hicolor/48x48/apps/konqueror.png
        divert_remove /usr/share/icons/hicolor/64x64/apps/konqueror.png
        divert_remove /usr/share/icons/hicolor/scalable/apps/konqueror.svgz
    ;;

    install)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0
