debian/tmp/opt/trinity/bin/kpersonalizer
debian/tmp/opt/trinity/share/applications/tde/kpersonalizer.desktop
debian/tmp/opt/trinity/share/applnk/System/kpersonalizer.desktop
debian/tmp/opt/trinity/share/apps/kpersonalizer/pics/step1.png
debian/tmp/opt/trinity/share/apps/kpersonalizer/pics/step2.png
debian/tmp/opt/trinity/share/apps/kpersonalizer/pics/step3.png
debian/tmp/opt/trinity/share/apps/kpersonalizer/pics/step4.png
debian/tmp/opt/trinity/share/apps/kpersonalizer/pics/step5.png
debian/tmp/opt/trinity/share/icons/crystalsvg/16x16/apps/kpersonalizer.png
debian/tmp/opt/trinity/share/icons/crystalsvg/32x32/apps/kpersonalizer.png

debian/icons/kpersonalizer.xpm		/opt/trinity/share/pixmaps
debian/icons/kpersonalizer-16.xpm	/opt/trinity/share/pixmaps
