#! /bin/sh -e

case "$1" in

    upgrade)
	rm -f /etc/trinity/debian/tdm-update-menu.sh
	rm -f /etc/trinity/debian/tdm.options
	rm -f /etc/trinity/tdm/pixmaps/XFree86bw.xpm
	rm -f /etc/trinity/tdm/pixmaps/XFree86.xpm
	rm -f /etc/trinity/tdm/Xresources
	rm -f /etc/menu-methods/tdm
    ;;

    install)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0
