debian/tmp/opt/trinity/include/kde/kprofilemethod.h
debian/tmp/opt/trinity/lib/kde3/kabcformat_kdeaccounts.la
debian/tmp/opt/trinity/lib/kde3/kabcformat_kdeaccounts.so
debian/tmp/opt/trinity/lib/kde3/plugins/styles/scheck.so
debian/tmp/opt/trinity/lib/kde3/plugins/styles/scheck.la
debian/tmp/opt/trinity/share/apps/kabc/formats/kdeaccountsplugin.desktop
debian/tmp/opt/trinity/share/apps/kstyle/themes/scheck.themerc
kdepalettes/kde_xpaintrc /opt/trinity/share/kdepalettes
kdepalettes/KDE_Gimp /opt/trinity/share/kdepalettes
kdepalettes/README /opt/trinity/share/kdepalettes
