/opt/trinity/share/apps/kgoldrunner/*
/opt/trinity/share/icons/hicolor/16x16/apps/kgoldrunner.png
/opt/trinity/share/icons/hicolor/22x22/apps/kgoldrunner.png
/opt/trinity/share/icons/hicolor/32x32/apps/kgoldrunner.png
/opt/trinity/share/icons/hicolor/48x48/apps/kgoldrunner.png
/opt/trinity/share/icons/hicolor/64x64/apps/kgoldrunner.png
/opt/trinity/share/icons/hicolor/128x128/apps/kgoldrunner.png
/opt/trinity/share/applications/kde/KGoldrunner.desktop
/opt/trinity/games/kgoldrunner
/opt/trinity/share/doc/kde/HTML/en/kgoldrunner/*
../icons/kgoldrunner.xpm /opt/trinity/share/pixmaps
../icons/kgoldrunner-16.xpm /opt/trinity/share/pixmaps
