/opt/trinity/share/apps/klines/*
/opt/trinity/share/applications/kde/klines.desktop
/opt/trinity/games/klines
/opt/trinity/share/config.kcfg/klines.kcfg
/opt/trinity/share/doc/tde/HTML/en/klines/*
/opt/trinity/share/icons/hicolor/128x128/apps/klines.png
/opt/trinity/share/icons/hicolor/64x64/apps/klines.png
/opt/trinity/share/icons/hicolor/48x48/apps/klines.png
/opt/trinity/share/icons/hicolor/32x32/apps/klines.png
/opt/trinity/share/icons/hicolor/22x22/apps/klines.png
/opt/trinity/share/icons/hicolor/16x16/apps/klines.png
../icons/klines.xpm /opt/trinity/share/pixmaps
../icons/klines-16.xpm /opt/trinity/share/pixmaps
