/opt/trinity/games/kreversi
/opt/trinity/share/doc/kde/HTML/en/kreversi/*
/opt/trinity/share/applications/kde/kreversi.desktop
/opt/trinity/share/apps/kreversi/*
/opt/trinity/share/config.kcfg/kreversi.kcfg
/opt/trinity/share/icons/crystalsvg/48x48/actions/lastmoves.png
/opt/trinity/share/icons/crystalsvg/48x48/actions/legalmoves.png
/opt/trinity/share/icons/crystalsvg/32x32/actions/lastmoves.png
/opt/trinity/share/icons/crystalsvg/32x32/actions/legalmoves.png
/opt/trinity/share/icons/crystalsvg/22x22/actions/lastmoves.png
/opt/trinity/share/icons/crystalsvg/22x22/actions/legalmoves.png
/opt/trinity/share/icons/crystalsvg/16x16/actions/lastmoves.png
/opt/trinity/share/icons/crystalsvg/16x16/actions/legalmoves.png
/opt/trinity/share/icons/crystalsvg/scalable/actions/lastmoves.svgz
/opt/trinity/share/icons/crystalsvg/scalable/actions/legalmoves.svgz
/opt/trinity/share/icons/hicolor/128x128/apps/kreversi.png
/opt/trinity/share/icons/hicolor/64x64/apps/kreversi.png
/opt/trinity/share/icons/hicolor/48x48/apps/kreversi.png
/opt/trinity/share/icons/hicolor/32x32/apps/kreversi.png
/opt/trinity/share/icons/hicolor/22x22/apps/kreversi.png
/opt/trinity/share/icons/hicolor/16x16/apps/kreversi.png
../icons/kreversi.xpm /opt/trinity/share/pixmaps
../icons/kreversi-16.xpm /opt/trinity/share/pixmaps
