opt/kde3/lib/kde3/kcm_serviceconfig.so.0.0.0 opt/kde3/lib/
opt/kde3/lib/kde3/kcm_serviceconfig.la opt/kde3/lib/
opt/kde3/lib/kde3/kcm_serviceconfig.a opt/kde3/lib/
opt/kde3/lib/kde3/kcm_userconfig.so.0.0.0 opt/kde3/lib/
opt/kde3/lib/kde3/kcm_userconfig.la opt/kde3/lib/
opt/kde3/lib/kde3/kcm_userconfig.a opt/kde3/lib/
opt/kde3/lib/kde3/kcm_mountconfig.so.0.0.0 opt/kde3/lib/
opt/kde3/lib/kde3/kcm_mountconfig.la opt/kde3/lib/
opt/kde3/lib/kde3/kcm_mountconfig.a opt/kde3/lib/
opt/kde3/lib/kde3/kcm_displayconfig.so.0.0.0 opt/kde3/lib/
opt/kde3/lib/kde3/kcm_displayconfig.la opt/kde3/lib/
opt/kde3/lib/kde3/kcm_displayconfig.a opt/kde3/lib/
opt/kde3/lib/kde3/kcm_wineconfig.so.0.0.0 opt/kde3/lib/
opt/kde3/lib/kde3/kcm_wineconfig.la opt/kde3/lib/
opt/kde3/lib/kde3/kcm_wineconfig.a opt/kde3/lib/
opt/kde3/share/icons/crystalsvg/32x32/apps/daemons.png
opt/kde3/share/icons/crystalsvg/32x32/apps/disksfilesystems.png
opt/kde3/share/icons/crystalsvg/32x32/apps/userconfig.png
opt/kde3/share/icons/crystalsvg/32x32/apps/displayconfig.png
opt/kde3/share/icons/crystalsvg/32x32/apps/wineconfig.png
opt/kde3/share/doc/kde/HTML/en/guidance/index.cache.bz2
opt/kde3/share/doc/kde/HTML/en/guidance/index.html
opt/kde3/share/doc/kde/HTML/en/guidance/introduction.html
opt/kde3/share/doc/kde/HTML/en/guidance/using-testapp.html
opt/kde3/share/doc/kde/HTML/en/guidance/commands.html
opt/kde3/share/doc/kde/HTML/en/guidance/developers.html
opt/kde3/share/doc/kde/HTML/en/guidance/re-1007-unmanagechildren-1.html
opt/kde3/share/doc/kde/HTML/en/guidance/faq.html
opt/kde3/share/doc/kde/HTML/en/guidance/credits.html
opt/kde3/share/doc/kde/HTML/en/guidance/installation.html
opt/kde3/share/doc/kde/HTML/en/guidance/requirements.html
opt/kde3/share/doc/kde/HTML/en/guidance/compilation.html
opt/kde3/share/doc/kde/HTML/en/guidance/configuration.html
opt/kde3/share/applications/kde/serviceconfig.desktop
opt/kde3/share/applications/kde/userconfig.desktop
opt/kde3/share/applications/kde/mountconfig.desktop
opt/kde3/share/applications/kde/displayconfig.desktop
opt/kde3/share/applications/kde/wineconfig.desktop
opt/kde3/share/apps/guidance/pics/laserwarn.png
opt/kde3/share/apps/guidance/pics/hi32-app-daemons.png
opt/kde3/share/apps/guidance/pics/hi16-encrypted.png
opt/kde3/share/apps/guidance/pics/hi32-user.png
opt/kde3/share/apps/guidance/pics/hi32-group.png
opt/kde3/share/apps/guidance/pics/hi32-identity.png
opt/kde3/share/apps/guidance/pics/hi32-password.png
opt/kde3/share/apps/guidance/pics/kcmpartitions.png
opt/kde3/share/apps/guidance/pics/kde1.png
opt/kde3/share/apps/guidance/pics/kde2.png
opt/kde3/share/apps/guidance/pics/kde3.png
opt/kde3/share/apps/guidance/pics/kde4.png
opt/kde3/share/apps/guidance/pics/kde5.png
opt/kde3/share/apps/guidance/pics/kde6.png
opt/kde3/share/apps/guidance/pics/hi32-samba.png
opt/kde3/share/apps/guidance/pics/hi16-hdd.png
opt/kde3/share/apps/guidance/pics/hi16-cdrom.png
opt/kde3/share/apps/guidance/pics/hi16-burner.png
opt/kde3/share/apps/guidance/pics/hi16-floppy.png
opt/kde3/share/apps/guidance/pics/hi16-blockdevice.png
opt/kde3/share/apps/guidance/pics/hi16-password.png
opt/kde3/share/apps/guidance/pics/hi16-memory.png
opt/kde3/share/apps/guidance/pics/hi16-network.png
opt/kde3/share/apps/guidance/pics/hi16-lock.png
opt/kde3/share/apps/guidance/pics/hi16-usbpen.png
opt/kde3/share/apps/guidance/pics/greenled.png
opt/kde3/share/apps/guidance/pics/greyled.png
opt/kde3/share/apps/guidance/pics/exec.png
opt/kde3/share/apps/guidance/pics/file.png
opt/kde3/share/apps/guidance/pics/important.png
opt/kde3/share/apps/guidance/pics/tux.png
opt/kde3/share/apps/guidance/pics/user.png
opt/kde3/share/apps/guidance/pics/energystar.png
opt/kde3/share/apps/guidance/pics/hi32-gfxcard.png
opt/kde3/share/apps/guidance/pics/hi32-display.png
opt/kde3/share/apps/guidance/pics/32-wine.png
opt/kde3/share/apps/guidance/pics/kdewinewizard.png
opt/kde3/share/apps/guidance/pics/displayconfig
opt/kde3/share/apps/guidance/pics/displayconfig/dualhead
opt/kde3/share/apps/guidance/pics/displayconfig/dualhead/monitor_1.png
opt/kde3/share/apps/guidance/pics/displayconfig/dualhead/monitor_2.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/background.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/background_r90.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/background_wide.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/background_wide_r90.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/monitor.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/monitor_r90.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/monitor_wide.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/monitor_wide_r90.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/window_4th.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/window_bottom_left_4th.png
opt/kde3/share/apps/guidance/pics/displayconfig/monitor_resizable/window_bottom_right_4th.png
opt/kde3/share/apps/guidance/pics/displayconfig/gammapics
opt/kde3/share/apps/guidance/pics/displayconfig/gammapics/MGam14.png
opt/kde3/share/apps/guidance/pics/displayconfig/gammapics/MGam16.png
opt/kde3/share/apps/guidance/pics/displayconfig/gammapics/MGam18.png
opt/kde3/share/apps/guidance/pics/displayconfig/gammapics/MGam20.png
opt/kde3/share/apps/guidance/pics/displayconfig/gammapics/MGam22.png
opt/kde3/share/apps/guidance/pics/displayconfig/gammapics/MGam24.png
opt/kde3/share/python-support/kde-guidance-kde3/SMBShareSelectDialog.py
opt/kde3/share/python-support/kde-guidance-kde3/SimpleCommandRunner.py
opt/kde3/share/python-support/kde-guidance-kde3/displayconfig.py
opt/kde3/share/python-support/kde-guidance-kde3/displayconfigwidgets.py
opt/kde3/share/python-support/kde-guidance-kde3/fuser.py
opt/kde3/share/python-support/kde-guidance-kde3/fuser_ui.py
#opt/kde3/share/python-support/kde-guidance-kde3/grubconfig.py
opt/kde3/share/python-support/kde-guidance-kde3/ktimerdialog.py
opt/kde3/share/python-support/kde-guidance-kde3/mountconfig.py
opt/kde3/share/python-support/kde-guidance-kde3/servertestdialog.py
opt/kde3/share/python-support/kde-guidance-kde3/serviceconfig.py
opt/kde3/share/python-support/kde-guidance-kde3/sizeview.py
opt/kde3/share/python-support/kde-guidance-kde3/unixauthdb.py
opt/kde3/share/python-support/kde-guidance-kde3/userconfig.py
opt/kde3/share/python-support/kde-guidance-kde3/wineconfig.py
opt/kde3/lib/kde3/kcm_serviceconfig.so.0 opt/kde3/lib/
opt/kde3/lib/kde3/kcm_serviceconfig.so opt/kde3/lib/
opt/kde3/lib/kde3/kcm_userconfig.so.0 opt/kde3/lib/
opt/kde3/lib/kde3/kcm_userconfig.so opt/kde3/lib/
opt/kde3/lib/kde3/kcm_mountconfig.so.0 opt/kde3/lib/
opt/kde3/lib/kde3/kcm_mountconfig.so opt/kde3/lib/
opt/kde3/lib/kde3/kcm_displayconfig.so.0 opt/kde3/lib/
opt/kde3/lib/kde3/kcm_displayconfig.so opt/kde3/lib/
opt/kde3/lib/kde3/kcm_wineconfig.so.0 opt/kde3/lib/
opt/kde3/lib/kde3/kcm_wineconfig.so opt/kde3/lib/
usr/share/lintian/overrides/kde-guidance-kde3
etc/X11/Xsession.d/40guidance-displayconfig_restore
