debian/tmp/opt/trinity/bin/rbkdesh
debian/tmp/opt/trinity/bin/rbkdeapi
debian/tmp/opt/trinity/bin/krubyinit
debian/tmp/opt/trinity/bin/rbtdeconfig_compiler

debian/tmp/opt/trinity/lib/ruby/*/Korundum.rb
debian/tmp/opt/trinity/lib/ruby/*/KDE/korundum.rb

debian/tmp/opt/trinity/lib/ruby/*/*/korundum.so*
debian/tmp/opt/trinity/lib/ruby/*/*/korundum.la

korundum/ChangeLog /opt/trinity/share/doc/libkorundum0-ruby1.8
