debian/tmp/opt/kde3/lib/libkjsembed.so.1.0.0
debian/tmp/opt/kde3/lib/libkjsembed.so.1

debian/tmp/opt/kde3/lib/kde3/libimagefxplugin.la
debian/tmp/opt/kde3/lib/kde3/libimagefxplugin.so
debian/tmp/opt/kde3/share/services/imagefx_plugin.desktop

debian/tmp/opt/kde3/lib/kde3/libqprocessplugin.so
debian/tmp/opt/kde3/lib/kde3/libqprocessplugin.la
debian/tmp/opt/kde3/share/services/qprocess_plugin.desktop

debian/tmp/opt/kde3/lib/kde3/libfileitemplugin.la
debian/tmp/opt/kde3/lib/kde3/libfileitemplugin.so
debian/tmp/opt/kde3/share/services/kfileitem_plugin.desktop

debian/tmp/opt/kde3/share/apps/kjsembed/cmdline.js
debian/tmp/opt/kde3/share/servicetypes/binding_type.desktop

debian/tmp/opt/kde3/bin/embedjs
debian/tmp/opt/kde3/share/apps/embedjs/embedjsui.rc
debian/tmp/opt/kde3/share/applnk/Utilities/embedjs.desktop
debian/tmp/opt/kde3/share/icons/hicolor/16x16/apps/embedjs.png
debian/tmp/opt/kde3/share/icons/hicolor/32x32/apps/embedjs.png

debian/tmp/opt/kde3/lib/kde3/libjavascript.la
debian/tmp/opt/kde3/lib/kde3/libjavascript.so
debian/tmp/opt/kde3/share/apps/kate/scripts/swaptabs.js
debian/tmp/opt/kde3/share/apps/kate/scripts/swaptabs.ui
debian/tmp/opt/kde3/share/apps/kate/scripts/swaptabs.desktop
debian/tmp/opt/kde3/share/services/javascript.desktop

kjsembed/docs/ChangeLog /opt/kde3/share/doc/libkjsembed1
