debian/tmp/opt/trinity/bin/ksysv
debian/tmp/opt/trinity/share/applications/kde/ksysv.desktop
debian/tmp/opt/trinity/share/apps/ksysv/ksysvui.rc
debian/tmp/opt/trinity/share/apps/ksysv/pics/ksysv_locked.png
debian/tmp/opt/trinity/share/apps/ksysv/pics/ksysv_restart.png
debian/tmp/opt/trinity/share/apps/ksysv/pics/ksysv_start.png
debian/tmp/opt/trinity/share/apps/ksysv/pics/ksysv_stop.png
debian/tmp/opt/trinity/share/apps/ksysv/pics/ksysv_unlocked.png
debian/tmp/opt/trinity/share/doc/kde/HTML/en/ksysv/common
debian/tmp/opt/trinity/share/doc/kde/HTML/en/ksysv/index.cache.bz2
debian/tmp/opt/trinity/share/doc/kde/HTML/en/ksysv/index.docbook
debian/tmp/opt/trinity/share/icons/crystalsvg/16x16/actions/toggle_log.png
debian/tmp/opt/trinity/share/icons/hicolor/16x16/apps/ksysv.png
debian/tmp/opt/trinity/share/icons/hicolor/22x22/apps/ksysv.png
debian/tmp/opt/trinity/share/icons/hicolor/32x32/apps/ksysv.png
debian/tmp/opt/trinity/share/icons/hicolor/48x48/apps/ksysv.png
debian/tmp/opt/trinity/share/mimelnk/application/x-ksysv.desktop
debian/tmp/opt/trinity/share/mimelnk/text/x-ksysv-log.desktop

debian/icons/ksysv.xpm		/opt/trinity/share/pixmaps
debian/icons/ksysv-16.xpm	/opt/trinity/share/pixmaps
