#! /bin/sh -e

case "$1" in

    configure)
	dpkg-divert --remove /usr/share/icons/hicolor/16x16/apps/kfind.png
        dpkg-divert --remove /usr/share/icons/hicolor/22x22/apps/kfind.png
        dpkg-divert --remove /usr/share/icons/hicolor/32x32/apps/kfind.png
        dpkg-divert --remove /usr/share/icons/hicolor/48x48/apps/kfind.png
        dpkg-divert --remove /usr/share/icons/hicolor/64x64/apps/kfind.png
    ;;

    install)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0
