debian/tmp/opt/trinity/bin/rbqtsh
debian/tmp/opt/trinity/bin/rbqtapi
debian/tmp/opt/trinity/bin/rbuic
debian/tmp/opt/trinity/bin/qtrubyinit

debian/tmp/opt/trinity/lib/ruby/1.8/Qt/qtruby.rb
debian/tmp/opt/trinity/lib/ruby/1.8/Qt.rb

debian/tmp/opt/trinity/lib/ruby/1.8/*/qtruby.so*
debian/tmp/opt/trinity/lib/ruby/1.8/*/qtruby.la

debian/tmp/opt/trinity/lib/ruby/1.8/*/tqui.so*
debian/tmp/opt/trinity/lib/ruby/1.8/*/tqui.la

qtruby/ChangeLog /opt/trinity/share/doc/libqt0-ruby1.8
