#! /bin/sh

set -e

package_name=synaptic-trinity

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    # remove old diversions if present
    # add new diversion
    dpkg-divert --package $package_name \
    --divert /usr/share/applications/synaptic.desktop.distrib \
    --rename /usr/share/applications/synaptic.desktop
    ;;

  upgrade)
    ;;

  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
